var resourceInfo={
ids_error: 'Error!',
ids_login: 'Login',
ids_auto: 'AUTO',
ids_automatic: 'Automatic',
ids_manual: 'Manual',
ids_enable: 'Enable',
ids_validate: 'Validate',
ids_modify: 'Modify',
ids_disable: 'Disable',
ids_subnetMask: 'Subnet Mask',
ids_allow: 'Allow',
ids_deny: 'Deny',
ids_day: 'day',
ids_days: 'days',
ids_hour: 'hour',
ids_hours: 'hours',
ids_minute: 'minute',
ids_minutes: 'minutes',
ids_requestError: 'No response, the device may have been disconnected, Please restart the device and try again.',
ids_success: 'Succeeded!',
ids_fail: 'Failed!',
ids_back: 'Back',
ids_icon_battery: 'Battery',
ids_icon_timeElapsed: 'Time elapsed',
ids_icon_debit: 'Debit',
ids_icon_people: 'People',
ids_icon_downloaded: 'Downloaded',
ids_icon_uploaded: 'Uploaded',
ids_menu_connection: 'Connection',
ids_menu_sms: 'SMS',
ids_menu_settings: 'Settings',
ids_menu_smsSettings: 'SMS Settings',
ids_menu_connectDevice: 'Connected Device(s)',
ids_menu_usage: 'Usage',
ids_menu_sharing: 'Sharing',
ids_menu_usageSetting: 'Usage Settings',
ids_menu_more: 'More',
ids_menu_language:'Language',
ids_foot_copyright: 'Copyright 2014-2016 TCL Communication Ltd.All Rights Reserved.',
ids_btn_help: 'Help',
ids_btn_logout: 'Logout',
ids_btn_block: 'Block',
ids_btn_unblock: 'Unblock',
ids_btn_apply: 'Apply',
ids_btn_cancel: 'Cancel',
ids_btn_next: 'Next',
ids_btn_continue: 'Continue',
ids_btn_save: 'Save',
ids_btn_new: 'New',
ids_btn_edit: 'Edit',
ids_btn_delete: 'Delete',
ids_btn_setDefault: 'Set&nbsp;Default',
ids_btn_refresh: 'Refresh',
ids_btn_select: 'Select',
ids_btn_reboot: 'Reboot',
ids_btn_reset: 'Reset',
ids_btn_backup: 'Backup',
ids_btn_restore: 'Restore',
ids_btn_ok: 'OK',
ids_btn_previous: 'Previous',
ids_btn_add: 'Add',
ids_title_wps: 'WPS',
ids_title_advanced: 'Advanced Settings',
ids_title_blockDevice: 'Block Device',
ids_title_connectMode: 'Connection Mode',
ids_title_networkMode: 'Network Mode',
ids_title_macFilter: 'MAC Filter',
ids_title_loginSettings: 'Login Settings',
ids_title_pinCodeSettings: 'Pin Code Settings',
ids_title_profilesManagement: 'Profiles Management',
ids_title_wifiSettings: 'WIFI Settings',
ids_title_about: 'About',
ids_title_tr069:'TR069',
ids_net_registing: 'Registering......',
ids_net_select: 'Network Selection',
ids_net_4gOnly: '4G Only',
ids_net_3gOnly: '3G Only',
ids_net_2gOnly: '2G Only',
ids_net_operator: 'Operator',
ids_net_noService: 'No Service',
ids_net_service: 'Service',
ids_net_status: 'Status',
ids_net_searching: 'Searching......',
ids_net_gsm: '2G',
ids_net_umts: '3G',
ids_net_lte: '4G',
ids_net_active: 'Active',
ids_net_available: 'Available',
ids_net_forbid: 'Forbidden',
ids_net_selectWarn: 'Please select one network!',
ids_sim_pinManagement: 'PIN Code Management',
ids_sim_remainTime: 'Remaining Attempt(s)',
ids_sim_pinCode: 'PIN code',
ids_sim_pukCode: 'PUK code',
ids_sim_simLockCode: 'SIMLock Code',
ids_sim_newPinCode: 'New PIN code',
ids_sim_confirmPinCode: 'Confirmed PIN code',
ids_sim_lockForbidden: 'SIM LOCK is forbidden!',
ids_sim_noSimCard: 'No SIM Card',
ids_sim_invalidSimCard: 'Invalid SIM Card',
ids_sim_pinNotAvailable: 'PIN code is not available.',
ids_sim_initializing: 'SIM is Initializing.',
ids_sim_pinRequired: 'PIN Required',
ids_sim_pukRequired: 'PUK Required',
ids_sim_unknown: 'Unknown',
ids_sim_nck: 'NCK',
ids_sim_nsck: 'NSCK',
ids_sim_spck: 'SPCK',
ids_sim_cck: 'CCK',
ids_sim_pck: 'PCK',
ids_sim_rck: 'RCK',
ids_sim_simLocked: 'SIM Lock Required',
ids_sim_pinRequiredTips: 'For more information, please click "PIN required" to unlock at first.',
ids_sim_pukRequiredTips: 'For more information, please click "PUK Required" to unlock at first.',
ids_sim_simLockedTips: 'For more information, please click "SIM Lock Required" to unlock at first.',
ids_sim_pinConfirmed: 'The confirmed PIN code should be the same as new PIN code.',
ids_sim_pinRule: 'PIN code should be 4-8 digits.',
ids_sim_pukRule: 'PUK code should be 8 digits.',
ids_sim_newPinRule: 'New PIN code should be 4-8 digits.',
ids_sim_comfirmPinRule: 'Confirmed PIN code should be 4-8 digits.',
ids_sim_lockCodeRule: 'SIM Lock code should be 10 digits.',
ids_sim_pinEnable: 'PIN auto validation is enabled.',
ids_sim_pinDisable: 'PIN auto validation is disabled.',
ids_sim_autoPinState: 'Current Status',
ids_sim_autoValidate: 'Auto validate',
ids_sim_pinCodeOperation: 'PIN Code Operation',
ids_sim_pinError: 'Pin error!',
ids_sim_changePinError: 'Change pin error!',
ids_sim_pukError: 'Puk error!',
ids_sim_simlockError: 'Simlock error!',
ids_sim_autoPin: 'PIN Code Auto Validation',
ids_sim_autoPinError: 'Auto pin verfiy error!',
ids_profile_password: 'Password',
ids_profile_profileName: 'Profile Name',
ids_profile_userName: 'User name',
ids_profile_apn: 'APN',
ids_profile_protocal: 'Protocol',
ids_profile_deleteWarn: 'Are you sure to delete it?',
ids_profile_inputName: 'Please input the profile name before saving it.',
ids_profile_profileNameRule: 'The maximum length of Profile name is 31,except for: , " : ; \\ & % + < > ?.',
ids_profile_userNameRule: 'The maximum length of User name is 31, except for: " : ; & \\.',
ids_profile_inputDialNum: 'Please input the dial number!',
ids_profile_inputApn: 'Please input the APN!',
ids_profile_numRule: 'Note: The max number of the profile you can create is 15.',
ids_profile_dialNumber: 'Dial Number',
ids_profile_inputRule: 'APN & Dial Number should be ASCII characters ranging from 32-127, except for: " : ; & \\.',
ids_profile_pwdRule: 'The maximum length of Password is 31,except for: " : ; & \\.',
ids_profile_nameWarn: 'The profile name already existed.',
ids_usage_duration: 'Duration Time',
ids_usage_clearHistory: 'Are you sure to reset all statistics?',
ids_usage_clear: 'Clear history',
ids_usage_home: 'Home',
ids_usage_roaming: 'Roaming',
ids_usage_of: 'of',
ids_usage_billingDay: 'Billing Day',
ids_usage_monthlyDataPlan: 'Monthly Data Plan',
ids_usage_dataConsumption: 'Data Consumption',
ids_usage_day: 'day',
ids_usage_timeLimit: 'Time Limit',
ids_usage_setTimeLimit: 'Set Time Limit',
ids_usage_minutesTimes: 'min(s)',
ids_usage_hrs: 'Hrs',
ids_usage_timePassed: 'Time Passed',
ids_usage_autoDisconnected: 'Auto Disconnected',
ids_usage_dataUsageReach: 'When data usage reaches Monthly Data Plan',
ids_usage_hours: 'hours',
ids_usage_minutes: 'minutes',
ids_usage_billingTimeTips: 'Please input the day between 1-31.',
ids_usage_mothlyDataTips: 'Please input the data between 1-1024.',
ids_usage_startTimeTips: 'Please input the data between 1-43200.',
ids_wifi_offRule: 'WIFI is disabled currently as no client connected for a long time.  Please enable WIFI manually by pressing any button on device if you want to use WIFI.',
ids_wifi_wifi: 'WiFi',
ids_wifi_on: 'On',
ids_wifi_off: 'Off',
ids_wifi_ssidBroadcast: 'SSID Broadcast',
ids_wifi_securityDisableDes: 'Disable means to cancel the Wi-Fi key.',
ids_wifi_cipher: 'Cipher Type',
ids_wifi_wpaTkip: 'TKIP',
ids_wifi_wpaAes: 'AES',
ids_wifi_showPwd: 'Show Password',
ids_wifi_wpa: 'WPA PSK',
ids_wifi_wpa2: 'WPA2 PSK',
ids_wifi_wepDescription: 'WEP Key is 5 or 13 ASCII characters,or 10 or 26 hexadecimal digits.',
ids_wifi_wpaDescription: 'The WPA Pre-Shared Key (PSK) should be 8-63 ASCII characters.',
ids_wifi_wpaRule: 'WPA PSK should be ASCII characters ranging from 32-127, except for: " : ; & \\.',
ids_wifi_wepRule: 'WEP Key should be ASCII characters ranging from 32-127, except for: " : ; & \\.',
ids_wifi_disconWarning: 'This action will disconnect the Wi-Fi. Are you sure to continue?',
ids_wifi_maxSsid: 'The maximum length of SSID is 32 characters, including 0-9, a-z, A-Z, "-", "_", "." ," ".',
ids_wifi_inputSsid: 'Please input the SSID.',
ids_wifi_wep: 'WEP',
ids_wifi_wpaWpa2Psk: 'WPA/WPA2 PSK',
ids_wifi_wepOpen: 'Open',
ids_wifi_wepShare: 'Share',
ids_wifi_wpsActiveWarn: 'WPS procedure is going on.Please try again two minutes later!',
ids_wifi_ssid2: 'SSID2.4GHz',
ids_wifi_cannotSet: 'The Wi-Fi is disable right now, can’t process this option.',
ids_wifi_wifiSecurity: 'WiFi Security',
ids_wifi_apIsotation: 'AP Isotation',
ids_wifi_802mode: '802.11 Mode',
ids_wifi_channel: 'WiFi Channel',
ids_wifi_maxUser: 'Max Number of Users',
ids_wifi_encryption: 'Encryption',
ids_wifi_key: 'Key',
ids_wifi_pbc: 'PBC',
ids_wifi_pbcConfiguration: 'Push Button Configuration',
ids_wifi_wpsPin: 'WPS PIN',
ids_wifi_pbcDecription: '1. Press WPS button of this device until WPS appears on the screen;<br/>2. On the Client (eg PC), open the Wi-Fi access utility and select the PBC;<br/>3. Click the icon on the top.',
ids_wifi_pinDecription: 'PIN:<br/>1. On the client (eg PC), open the Wi-Fi access utility and select the PIN method, then a 4 or 8 digits PIN code will be generated;<br/>2. Enable PIN and entered the 4 or 8 digits PIN code;<br/>3. Click &lt;Apply&gt;.',
ids_wifi_wpsActive: 'WPS is active.',
ids_wifi_wpsPinRule: 'WPS PIN code should be 4 or 8 digits.',
ids_wifi_notSuppotWepWpa: 'WPS is not available under WEP, WPA, WPA2 TKIP !',
ids_wifi_notSuppotMacFilter: 'WPS (2.0 version) procedure cannot be activated if Mac address filter is enabled.',
ids_wifi_offTip: 'The Wifi is disable, Please try again after open the wifi.',
ids_wifi_wpsNotSuppotSSIDHidden: 'SSID Hidden,can not set WPS.',
ids_login_loginPwd: 'Login Password',
ids_login_newPwd: 'New Password',
ids_login_confirmPwdRule: 'The new password is not the same as the confirmed one.',
ids_login_inputCurrPwd: 'Current Password is wrong.',
ids_login_wrongPwd: 'Wrong password!',
ids_login_otherLogin: 'The administrator had already logged in, Please try later.',
ids_login_timeuseout: 'The login times used out.Please reboot and try again.',
ids_login_inputOldPwd: 'Please input the old password.',
ids_login_inputNewPwd: 'Please input the new password.',
ids_login_inputConfirmPwd: 'Please input the Confirmed Password.',
ids_login_checkPwdRule: 'Invalid password!The length of login password is 4-16, including 0-9, a-z, A-Z,"-+!@$#^&*",please input again.',
ids_login_inputPwd: 'Please input the password.',
ids_login_nameOrPwdWrong: 'User name or password is wrong!',
ids_login_confirmPwd: 'Confirm Password',
ids_router_homeAddr: 'Home Address',
ids_ipAddress: 'IP Address',
ids_router_dhcpServer: 'DHCP Server',
ids_router_leaseTime: 'DHCP IP Lease Time',
ids_router_restartWarn: 'This action requires the device to be restarted. Are you sure to continue?',
ids_router_ipAddrEmpty: 'IP Address is empty. Please input again!',
ids_router_ipAddrInvalid: 'IP Address is invalid. Please input again!',
ids_router_subnetEmpty: 'Subnet mask is empty. Please input again!',
ids_router_subnetInvalid: 'Subnet mask is invalid. Please input again!',
ids_router_startIpInvalid: 'Start IP Address is invalid. Please input again!',
ids_router_startIpEmpty: 'Start IP Address is empty. Please input again!',
ids_router_endIpInvalid: 'End IP Address is invalid. Please input again!',
ids_router_endIpEmpty: 'End IP Address is empty. Please input again!',
ids_router_startSameSubnet: 'Start IP Address and "IP Address" should belong to the same subnet.',
ids_router_endSameSubnet: 'End IP Address and "IP Address" should belong to the same subnet.',
ids_router_endGeaterStart: 'End IP Address should be greater than "Start IP Address".',
ids_router_startIP: 'Start IP',
ids_router_endIP: 'End IP',
ids_router_ipRule: 'Error!Please be noticed, 10 after the Home Address is System pre-reserved IP,and it can not be included in DHCP IP Pool.',
ids_sms_saveMode: 'Save Mode',
ids_sms_sendingPrompt: 'Sending......, please wait!',
ids_sms_inputNum: 'Please input a mobile number.',
ids_sms_mobileNumRule: 'The maximum length of Mobile number is 20 digits, including "+0123456789",please input again.',
ids_sms_deleteWarning: 'Are you sure to delete the message(s)?',
ids_sms_saveDevice: 'Device',
ids_sms_saveSimCard: 'SIM card',
ids_sms_smsFull: 'SMS box is full, please delete some SMS to be able to send/save new SMS.',
ids_sms_selectSomeOptions: '3 contacts at most',
ids_sms_selectAnOption: 'Select an Option',
ids_sms_chatInputConfirm: 'Please press Enter or enter ";" to complete',
ids_sms_phoneNumberInvalid: 'Phone number invalid',
ids_sms_draft: 'Draft',
ids_sms_saveDraftSuccess: 'SMS is saved as a draft',
ids_sms_saveDraftFailed: 'Draft save failed',
ids_sms_newMessageOn: 'unread of',
ids_sms_messageSending: 'There is a sms is sending',
ids_sms_newMessage: 'New Message',
ids_sms_deleteAll: 'Delete all',
ids_sms_centerNum: 'SMS Center',
ids_sms_report: 'SMS Report',
ids_sms_emptyMessageWarn: 'Message is empty. Are you sure to send this null message?',
ids_sms_numberWarning: 'The input is too much. Please delete some.',
ids_sms_sendFail: 'Send sms failed!',
ids_sms_delivered: 'Delivered',
ids_wan_connected: 'Connected',
ids_wan_connecting: 'Connecting......',
ids_wan_disconnected: 'Disconnected',
ids_wan_disconnecting: 'Disconnecting......',
ids_wan_tips: 'Failed! Usage history overflow,you can reset the Monthly Data Plan and then reconnect.',
ids_wan_roamingAutoConnect: 'Automatically connect even when in roaming.',
ids_wan_inputDeviceName: 'please input device name',
ids_wan_connectIPMode: 'Connection IP Mode',
ids_wan_cannotBlock: 'The Mac Filter is Allow right now, can’t process this option.',
ids_wan_Block: 'The MAC address list already full, can’t process this option.',
ids_sys_ipAddress: 'IP Address',
ids_sys_swVersion: 'Software Version',
ids_sys_hwVersion: 'Hardware Version',
ids_sys_imei: 'IMEI',
ids_sys_deviceName: 'Device Name',
ids_sys_macAddress: 'MAC Address',
ids_sys_rebootDecription: 'Click this button to restart the device.',
ids_sys_backupDecription: 'Download(Backup) the configuration.',
ids_sys_setRebootEvent: 'The device is rebooting, please wait 60 seconds,then reconnect to the Wi-Fi device.',
ids_sys_resetDecription: 'Restore Factory Default settings.',
ids_sys_selectFilePrompt: 'Please select a file before uploading.',
ids_sys_restoreBackupWarn: 'This action will update the settings and restart the device once the upload is completed. Are you sure to continue?',
ids_sys_restoreFactoryWarn: 'This action will restore the settings to factory default and restart the device. Are you sure to continue?',
ids_sys_system: 'System',
ids_sys_rebootWarn: 'Are you sure to restart this device?',
ids_security_macFilterDescription: 'Control and manage the device accessing the WLAN. (improve the security of WLAN).',
ids_security_macAddrInvalid: 'MAC Address is invalid.',
ids_security_macAddrNameWarn: 'The MAC Address already existed.',
ids_security_addMacAddress: 'Add MAC Address',
ids_sd_sdSharing: 'SD Card Sharing',
ids_sd_currentFolder: 'Current Folder',
ids_sd_dlna: 'DLNA',
ids_sd_close: 'Close',
ids_sd_serverName: 'Server Name',
ids_sd_dlnaDes: 'Turning on DLNA makes the media content on the microSD card avarilable to connected deviced.',
ids_sd_usedTotal: '(Used/Total)',
ids_sd_noSdCard: 'No SD Card',
ids_sd_viewFile: 'View File',
ids_sd_sdShareMode: 'SD Share Mode',
ids_sd_sdCard: 'SD Card',
ids_fota_checking: 'Checking…',
ids_fota_checkUpdate: 'Update',
ids_fota_updateTitle: 'System Updates',
ids_fota_upgrading: 'Upgrading.....',
ids_fota_upgradingTips: 'Please don\'t power off during upgrading.The device will be restarted after an upgrade.',
ids_fota_downloading: 'Downloading…',
ids_fota_batteryTips: 'Battery is low,the device can not be upgraded',
ids_fota_downloadError: 'Download error',
ids_fota_findNewVersion: 'Find new version',
ids_fota_updateDescription: 'click "Update" to update to new version.',
ids_fota_latestVersion: 'It\'s already the latest version.',
ids_fota_haveNewVersion: 'A new SW available, click to update.',
ids_more_onlineUpdate: 'Online Update',
ids_sys_chooseFile:'Choose File',
ids_sys_noFileChosen:'NO file Chosen',
ids_tr069_client:'TR-069 client – Configuration',
ids_tr069_tips:'Select the desired values and click “Apply/Save” to configure the TR-069 client options.',
ids_tr069_inform:'Inform',
ids_tr069_informInterval:'Inform Interval (s)',
ids_tr069_acsUrl:'ACS URL',
ids_tr069_acsUsername:'ACS User Name',
ids_tr069_acsPw:'ACS Password',
ids_tr069_connRqAuth:'Connection Request Authentication',
ids_tr069_connRqUsername:'Connection Request User Name',
ids_tr069_connRqPw:'Connection Request Password',
ids_tr069_inputInformInterval:'Please input the inform interval before saving it.',
ids_tr069_inputAcsUrl:'Please input the acs url before saving it.',
ids_tr069_inputAcsUserName:'Please input the acs user name before saving it.',
ids_tr069_inputAcsPassword:'Please input the acs password before saving it.',
ids_tr069_inputConReqUserName:'Please input the connection request user name before saving it.',
ids_tr069_inputConReqPassword:'Please input the connection request password before saving it.',
ids_tr069_informIntervalRule:'Inform interval should be 0-2678400,including "0123456789".',
ids_tr069_acsUrlRule:'Acs url format:eg:http://ip address:port/xxx',
ids_wifi_country:'Country',
ids_wifi_wlan_mode:'Wlan Mode'
}