var resourceInfo={
ids_error: 'Fehler!',
ids_login: 'Anmelden',
ids_auto: 'AUTO',
ids_automatic: 'Automatisch',
ids_manual: 'Manuell',
ids_enable: 'Aktivieren',
ids_validate: 'Überprüfen',
ids_modify: 'Ändern',
ids_disable: 'Deaktivieren',
ids_subnetMask: 'Subnetzmaske',
ids_allow: 'Zulassen',
ids_deny: 'Verweigern',
ids_day: 'Tag(e)',
ids_days: 'Tage',
ids_hour: 'Stunde',
ids_hours: 'Stunden',
ids_minute: 'Minute',
ids_minutes: 'Minute(n)',
ids_requestError: 'Keine Antwort. Die Verbindung zum Gerät wurde möglicherweise getrennt. Starten Sie das Gerät neu und versuchen Sie es erneut.',
ids_success: 'Erfolgreich!',
ids_fail: 'Ein Fehler ist aufgetreten.',
ids_back: 'Zurück',
ids_icon_battery: 'Akku',
ids_icon_timeElapsed: 'Verstrichene Zeit',
ids_icon_debit: 'Soll',
ids_icon_people: 'Kontakte',
ids_icon_downloaded: 'Heruntergeladen',
ids_icon_uploaded: 'Hochgeladen',
ids_menu_connection: 'Verbindung',
ids_menu_sms: 'SMS',
ids_menu_settings: 'Einstellungen',
ids_menu_smsSettings: 'SMS-Einstellung',
ids_menu_connectDevice: 'Verbundene Geräte',
ids_menu_usage: 'Nutzung',
ids_menu_sharing: 'Freigeben',
ids_menu_usageSetting: 'Nutzungseinstellungen',
ids_menu_more: 'Mehr',
ids_menu_language: 'Sprache',
ids_foot_copyright: 'Copyright 2014 bis 2016. TCL Communication Ltd. Alle Rechte vorbehalten.',
ids_btn_help: 'Hilfe',
ids_btn_logout: 'Abmelden',
ids_btn_block: 'Blockieren',
ids_btn_unblock: 'Blockierung aufh',
ids_btn_apply: 'Anwenden',
ids_btn_cancel: 'Abbrechen',
ids_btn_next: 'Weiter',
ids_btn_continue: 'Fortfahren',
ids_btn_save: 'Speichern',
ids_btn_new: 'Neu',
ids_btn_edit: 'Bearbeiten',
ids_btn_delete: 'Löschen',
ids_btn_setDefault: 'Standard festlegen',
ids_btn_refresh: 'Aktualisieren',
ids_btn_select: 'Auswählen',
ids_btn_reboot: 'Neustart',
ids_btn_reset: 'Zurücksetzen ',
ids_btn_backup: 'Sichern',
ids_btn_restore: 'Wiederherstellen',
ids_btn_ok: 'OK',
ids_btn_previous: 'Zurück',
ids_btn_add: 'Hinzufügen',
ids_title_wps: 'WPS',
ids_title_advanced: 'Erweiterte Einstellungen',
ids_title_blockDevice: 'Gerät sperren',
ids_title_connectMode: 'Verbindungsmodus',
ids_title_networkMode: 'Netzmodus',
ids_title_macFilter: 'MAC-Filter ',
ids_title_loginSettings: 'Anmeldeeinstellungen',
ids_title_pinCodeSettings: 'PIN-Code-Einstellungen',
ids_title_profilesManagement: 'Profilverwaltung',
ids_title_wifiSettings: 'WLAN-Einstellungen',
ids_title_about: 'Info',
ids_title_tr069: 'FernKonfiguration',
ids_net_registing: 'Registrierung wird durchgeführt...',
ids_net_select: 'Netzauswahl',
ids_net_4gOnly: 'Nur 4G',
ids_net_3gOnly: 'Nur 3G',
ids_net_2gOnly: 'Nur 2G',
ids_net_operator: 'Betreiber',
ids_net_noService: 'Kein Dienst',
ids_net_service: 'Service',
ids_net_status: 'Status',
ids_net_searching: 'Suche läuft...',
ids_net_gsm: '2G',
ids_net_umts: '3G',
ids_net_lte: '4G',
ids_net_active: 'Aktiv ',
ids_net_available: 'Verfügbar ',
ids_net_forbid: 'Verboten ',
ids_net_selectWarn: 'Wählen Sie ein Netz aus. ',
ids_sim_pinManagement: 'PIN-Verwaltung',
ids_sim_remainTime: 'Verbleibende Versuche',
ids_sim_pinCode: 'PIN',
ids_sim_pukCode: 'PUK',
ids_sim_simLockCode: 'SIM-Lock-Code',
ids_sim_newPinCode: 'Neue PIN',
ids_sim_confirmPinCode: 'PIN bestätigen',
ids_sim_lockForbidden: 'SIM-Sperre verboten.',
ids_sim_noSimCard: 'Keine SIM-Karte',
ids_sim_invalidSimCard: 'Ungültige SIM-Karte',
ids_sim_pinNotAvailable: 'PIN-Code nicht verfügbar.',
ids_sim_initializing: 'SIM wird initialisiert ',
ids_sim_pinRequired: 'PIN erforderlich',
ids_sim_pukRequired: 'PUK erforderlich',
ids_sim_unknown: 'Unbekannt',
ids_sim_nck: 'NCK',
ids_sim_nsck: 'NSCK',
ids_sim_spck: 'SPCK',
ids_sim_cck: 'CCK',
ids_sim_pck: 'PCK',
ids_sim_rck: 'RCK',
ids_sim_simLocked: 'SIM-Lock erforderlich',
ids_sim_pinRequiredTips: 'Wählen Sie zum Erhalten weiterer Informationen zunächst PIN erforderlich aus, um das Gerät zu entsperren.',
ids_sim_pukRequiredTips: 'Wählen Sie zum Erhalten weiterer Informationen zunächst PUK erforderlich aus, um das Gerät zu entsperren.',
ids_sim_simLockedTips: 'Wählen Sie zum Erhalten weiterer Informationen zunächst SIM-Lock erforderlich aus, um das Gerät zu entsperren.',
ids_sim_pinConfirmed: 'Die PIN zum Bestätigen muss mit der neuen PIN übereinstimmen.',
ids_sim_pinRule: 'Die PIN sollte aus 4-8 Ziffern bestehen.',
ids_sim_pukRule: 'Der PUK sollte aus 8 Ziffern bestehen.',
ids_sim_newPinRule: 'Der neue PIN-Code muss 4 bis 8 Ziffern umfassen.',
ids_sim_comfirmPinRule: 'Die Bestätigungs-PIN muss 4 bis 8 Ziffern umfassen.',
ids_sim_lockCodeRule: 'Der Code für die SIM-Sperre sollte 10 Ziffern lang sein.',
ids_sim_pinEnable: 'Die automatische PIN-Überprüfung ist aktiviert.',
ids_sim_pinDisable: 'Die automatische PIN-Überprüfung ist deaktiviert.',
ids_sim_autoPinState: 'Aktueller Status',
ids_sim_autoValidate: 'Automatische PIN-Eingabe',
ids_sim_pinCodeOperation: 'PIN-Code',
ids_sim_pinError: 'PIN-Fehler',
ids_sim_changePinError: 'Fehler beim Ändern der PIN',
ids_sim_pukError: 'PUK-Fehler',
ids_sim_simlockError: 'SIM-Lock-Fehler',
ids_sim_autoPin: 'Automatische PIN-Code-Überprüfung',
ids_sim_autoPinError: 'Fehler bei der automatischen PIN-Überprüfung',
ids_profile_password: 'Kennwort',
ids_profile_profileName: 'Profilname',
ids_profile_userName: 'Benutzername',
ids_profile_apn: 'APN',
ids_profile_protocal: 'Protokoll',
ids_profile_deleteWarn: 'Möchten Sie das Profil wirklich löschen?',
ids_profile_inputName: 'Geben Sie vor dem Speichern der Profileinstellungen den Profilnamen ein.',
ids_profile_profileNameRule: 'Der Profilname kann aus maximal 31 Zeichen bestehen, ausgenommen: , " : ; \\ & % + < > ?',
ids_profile_userNameRule: 'Der Benutzername darf maximal aus 31 Zeichen bestehen, ausgenommen: " : ; & \\.',
ids_profile_inputDialNum: 'Geben Sie die Profilnummer ein.',
ids_profile_inputApn: 'Geben Sie den APN ein.',
ids_profile_numRule: 'Hinweis: Sie können maximal 15 Profile erstellen.',
ids_profile_dialNumber: 'Rufnummer',
ids_profile_inputRule: 'Der Zugriffspunktname und die Rufnummer sollten aus 32 bis 127 ASCII-Zeichen bestehen, ausgenommen: " : ; & \\.',
ids_profile_pwdRule: 'Das Kennwort darf maximal aus 32 Zeichen bestehen, ausgenommen: " : ; & \\',
ids_profile_nameWarn: 'Dieser Profilname existiert bereits.',
ids_usage_duration: 'Dauer',
ids_usage_clearHistory: 'Möchten Sie wirklich alle Statistiken zurücksetzen?',
ids_usage_clear: 'Verlauf löschen',
ids_usage_home: 'Heimnetz',
ids_usage_roaming: 'Roaming',
ids_usage_of: 'von',
ids_usage_billingDay: 'Abrechnungstag',
ids_usage_monthlyDataPlan: 'Monatlicher Datentarif',
ids_usage_dataConsumption: 'Datenverbrauch',
ids_usage_day: 'Tag(e)',
ids_usage_timeLimit: 'Zeitlimit',
ids_usage_setTimeLimit: 'Zeitlimit festlegen',
ids_usage_minutesTimes: 'Minute(n)',
ids_usage_hrs: 'Std',
ids_usage_timePassed: 'Verstrichene Zeit',
ids_usage_autoDisconnected: 'Verbindung automatisch getrennt',
ids_usage_dataUsageReach: 'Wenn die Datennutzung den monatlichen Datentarif erreicht',
ids_usage_hours: 'Stunde(n)',
ids_usage_minutes: 'Minute(n) ',
ids_usage_billingTimeTips: 'Geben Sie einen Wert für den Tag von 1 bis 31 ein.',
ids_usage_mothlyDataTips: 'Geben Sie einen Wert für die Daten von 1 bis 1024 ein.',
ids_usage_startTimeTips: 'Geben Sie einen Wert für die Daten von 1 bis 43200 ein.',
ids_wifi_offRule: 'WLAN ist derzeit deaktiviert, da längere Zeit kein Client verbunden war.  Aktivieren Sie das WLAN zur Verwendung manuell, indem Sie eine beliebige Taste am Gerät drücken.',
ids_wifi_wifi: 'WLAN',
ids_wifi_on: 'Ein',
ids_wifi_off: 'Aus',
ids_wifi_ssidBroadcast: 'SSID-Broadcast',
ids_wifi_securityDisableDes: 'Vom Deaktivieren der Sicherheit wird abgeraten, da dadurch der Schutz für die WLAN-Verbindung aufgehoben wird.',
ids_wifi_cipher: 'Verschlüsselungsart',
ids_wifi_wpaTkip: 'TKIP',
ids_wifi_wpaAes: 'AES',
ids_wifi_showPwd: 'Kennwort anzeigen ',
ids_wifi_wpa: 'WPA-PSK',
ids_wifi_wpa2: 'WPA2-PSK',
ids_wifi_wepDescription: 'Der WEP-Schlüssel besteht aus 5 oder 13 ASCII-Zeichen bzw. 10 oder 26 hexadezimalen Ziffern.',
ids_wifi_wpaDescription: ' Der WPA-Pre-Shared Key (PSK) muss aus 8-63 ASCII-Zeichen oder 64 hexadezimalen Ziffern bestehen.',
ids_wifi_wpaRule: 'Der WPA-PSK sollte aus ASCII-Zeichen zwischen 32 und 127 bestehen, ausgenommen: " : ; & \\.',
ids_wifi_wepRule: 'Der WEP-Schlüssel sollte aus ASCII-Zeichen zwischen 32 und 127 bestehen, ausgenommen: " : ; & \\.',
ids_wifi_disconWarning: 'Bei dieser Aktion wird die WLAN-Verbindung deaktiviert. Möchten Sie dennoch fortfahren?',
ids_wifi_maxSsid: 'Die SSID kann maximal aus 32 Zeichen bestehen, darunter 0-9, a-z, A-Z, "-", "_", ".", " ".',
ids_wifi_inputSsid: 'Geben Sie die SSID ein.',
ids_wifi_wep: 'WEP',
ids_wifi_wpaWpa2Psk: 'WPA/WPA2 PSK',
ids_wifi_wepOpen: 'OPEN',
ids_wifi_wepShare: 'Shared ',
ids_wifi_wpsActiveWarn: 'Der WPS-Vorgang ist aktiv. Versuchen Sie es nach einigen Minuten erneut.',
ids_wifi_ssid2: 'SSID für 2,4 GHz',
ids_wifi_cannotSet: 'Diese Option kann nicht angewendet werden, weil WLAN derzeit deaktiviert ist.',
ids_wifi_wifiSecurity: 'WLAN-Sicherheit',
ids_wifi_apIsotation: 'AP-Isolierung',
ids_wifi_802mode: '802.11-Modus',
ids_wifi_channel: 'WLAN-Kanal',
ids_wifi_maxUser: 'Max. Benutzeranzahl',
ids_wifi_encryption: 'Verschlüsselung',
ids_wifi_key: 'Schlüssel',
ids_wifi_pbc: 'PBC',
ids_wifi_pbcConfiguration: 'Konfiguration auf Knopfdruck',
ids_wifi_wpsPin: 'WPS-PIN',
ids_wifi_pbcDecription: '1. Drücken Sie an diesem Gerät die WPS-Taste, bis auf dem Bildschirm WPS zu sehen ist.<br/>2. Öffnen Sie auf dem Client (z. B. einem Computer) das Hilfsprogramm für den WLAN-Zugriff und wählen Sie PBC aus.<br/>3. Klicken Sie oben auf das Symbol.',
ids_wifi_pinDecription: 'PIN:<br/>1. Öffnen Sie auf dem Client (z. B. einem Computer) das Hilfsprogramm für den WLAN-Zugriff und wählen Sie die PIN-Methode aus. Ein 4- bis 8-stelliger PIN-Code wird erstellt.<br/>2. Aktivieren Sie die PIN und geben Sie den 4- bis 8-stelligen PIN-Code ein.<br/>3. Klicken Sie auf &lt;Anwenden&gt;.',
ids_wifi_wpsActive: 'WPS aktiv.',
ids_wifi_wpsPinRule: 'Die WPS-PIN sollte aus 4 bis 8 Ziffern bestehen.',
ids_wifi_notSuppotWepWpa: 'WPS ist nicht mit WEP, WPA, WPA2 TKIP verfügbar.',
ids_wifi_notSuppotMacFilter: 'WPS (Version 2.0) kann nicht aktiviert werden, falls der MAC-Adressfilter aktiv ist.',
ids_wifi_offTip: 'WLAN ist deaktiviert. Versuchen Sie es erneut, nachdem Sie das WLAN geöffnet haben.',
ids_wifi_wpsNotSuppotSSIDHidden: 'SSID ausgeblendet, WPS kann nicht festgelegt werden',
ids_login_loginPwd: 'Anmeldekennwort',
ids_login_newPwd: 'Neues Kennwort',
ids_login_confirmPwdRule: 'Das neue Kennwort muss mit dem Kennwort zum Bestätigen übereinstimmen.',
ids_login_inputCurrPwd: 'Das aktuelle Passwort ist falsch.',
ids_login_wrongPwd: 'Falsches Passwort!',
ids_login_otherLogin: 'Der Administrator ist eingeloggt, Bitte versuchen Sie es später.',
ids_login_timeuseout: 'Die Zeit zum Anmelden ist abgelaufen. Starten Sie das Gerät neu und versuchen Sie es erneut.',
ids_login_inputOldPwd: 'Geben Sie das alte Passwort ein.',
ids_login_inputNewPwd: 'Geben Sie das neue Kennwort ein.',
ids_login_inputConfirmPwd: 'Geben Sie das bestätigte Passwort ein.',
ids_login_checkPwdRule: 'Ungültiges Passwort. Das Anmeldepasswort darf maximal 16 Zeichen lang sein, einschließlich 0-9, a-z, A-Z,"-+!@$#^&*". Bitte geben Sie es erneut ein.',
ids_login_inputPwd: 'Geben Sie das Passwort ein.',
ids_login_nameOrPwdWrong: 'Der Nutzername oder das Passwort ist falsch.',
ids_login_confirmPwd: 'Passwort bestätigen',
ids_router_homeAddr: 'Privatadresse',
ids_ipAddress: 'IP-Adresse',
ids_router_dhcpServer: 'DHCP-Server',
ids_router_leaseTime: 'DHCP-IP-Lease-Dauer',
ids_router_restartWarn: 'Für diese Aktion müssen Sie das Gerät neustarten. Möchten Sie fortfahren?',
ids_router_ipAddrEmpty: 'Die IP-Adresse ist leer. Geben Sie sie erneut ein.',
ids_router_ipAddrInvalid: 'Die IP-Adresse ist ungültig. Geben Sie sie erneut ein.',
ids_router_subnetEmpty: 'Sie Subnetzmaske ist leer. Geben Sie sie erneut ein.',
ids_router_subnetInvalid: 'Die Subnetzmaske ist ungültig. Geben Sie sie erneut ein.',
ids_router_startIpInvalid: 'Die Start-IP-Adresse ist ungültig. Geben Sie sie erneut ein.',
ids_router_startIpEmpty: 'Die Start-IP-Adresse ist leer. Geben Sie sie erneut ein.',
ids_router_endIpInvalid: 'Die End-IP-Adresse ist ungültig. Geben Sie sie erneut ein. ',
ids_router_endIpEmpty: 'Die End-IP-Adresse ist leer. Geben Sie sie erneut ein. ',
ids_router_startSameSubnet: '„Start-IP-Adresse“ und „IP-Adresse“ sollten zum selben Subnetz gehören.',
ids_router_endSameSubnet: '„End-IP-Adresse“ und „IP-Adresse“ sollten zum selben Subnetz gehören.',
ids_router_endGeaterStart: 'Die „End-IP-Adresse“ sollte länger sein als die „Start-IP-Adresse“.',
ids_router_startIP: 'Start-IP-Adresse',
ids_router_endIP: 'End-IP-Adresse',
ids_router_ipRule: 'Fehler! Beachten Sie, dass die „10“ nach der eigenen Adresse die für das System reservierte IP darstellt. Sie darf nicht im DHCP-IP-Pool enthalten sein.',
ids_sms_saveMode: 'Speichermodus',
ids_sms_sendingPrompt: 'Versand läuft... Bitte warten. ',
ids_sms_inputNum: 'Geben Sie eine Mobiltelefonnummer ein.',
ids_sms_mobileNumRule: 'Die Mobiltelefonnummer kann maximal aus 20 Zeichen bestehen, darunter „+0123456789“. Geben Sie die Nummer erneut ein.',
ids_sms_deleteWarning: 'Möchten Sie die Mitteilung(en) wirklich löschen?',
ids_sms_saveDevice: 'Gerät',
ids_sms_saveSimCard: 'SIM-Karte',
ids_sms_smsFull: 'Der SMS-Eingang ist voll. Löschen Sie einige SMS, um neue SMS senden und speichern zu können.',
ids_sms_selectSomeOptions: 'Maximal 3 Kontakte',
ids_sms_selectAnOption: 'Option auswählen',
ids_sms_chatInputConfirm: 'Drücken Sie abschließend die Eingabetaste oder geben Sie ; ein.',
ids_sms_phoneNumberInvalid: 'Ungültige Telefonnummer',
ids_sms_draft: 'Entwurf',
ids_sms_saveDraftSuccess: 'SMS als Entwurf gespeichert',
ids_sms_saveDraftFailed: 'Speichern des Entwurfs fehlgeschlagen',
ids_sms_newMessageOn: 'ungelesen von',
ids_sms_messageSending: 'SMS wird versendet',
ids_sms_newMessage: 'Neue Mitteilung',
ids_sms_deleteAll: 'Alle löschen',
ids_sms_centerNum: 'SMS-Center',
ids_sms_report: 'SMS-Bericht',
ids_sms_delivered: 'Zugestellt',
ids_sms_emptyMessageWarn: 'Die Mitteilung ist leer. Möchten Sie diese leere Mitteilung wirklich senden?',
ids_sms_numberWarning: 'Die Eingabe ist zu lang. Löschen Sie einige Buchstaben.',
ids_sms_sendFail: 'Senden der SMS fehlgeschlagen',
ids_wan_tips: 'Fehlgeschlagen. Überlauf bei der Nutzung. Sie können den monatlichen Datentarif zurücksetzen und erneut eine Verbindung herstellen.',
ids_wan_connected: 'Verbunden ',
ids_wan_connecting: 'Verbindung wird hergestellt... ',
ids_wan_disconnected: 'Verbindung getrennt',
ids_wan_disconnecting: 'Verbindung wird getrennt... ',
ids_wan_roamingAutoConnect: 'Verbindung automatisch herstellen (auch beim Roaming)',
ids_wan_inputDeviceName: 'Gerätenamen eingeben',
ids_wan_connectIPMode: 'Verbindung: IP-Modus',
ids_wan_cannotBlock: 'Für den MAC-Filter ist derzeit Zulassen eingestellt. Diese Option kann nicht ausgeführt werden.',
ids_wan_Block: 'Die Liste der MAC-Adressen ist bereits voll. Diese Option kann nicht ausgeführt werden.',
ids_sys_ipAddress: 'IP-Adresse',
ids_sys_swVersion: 'Softwareversion',
ids_sys_hwVersion: 'Hardwareversion',
ids_sys_imei: 'IMEI',
ids_sys_deviceName: 'Gerätename',
ids_sys_macAddress: 'MAC-Adresse',
ids_sys_rebootDecription: 'Drücken Sie zum Neustarten des Geräts diese Taste.',
ids_sys_backupDecription: 'Konfiguration herunterladen (sichern).',
ids_sys_setRebootEvent: 'Das Gerät startet neu. Warten Sie 60 Sekunden und stellen Sie anschließend erneut eine Verbindung zum WLAN-Gerät her.',
ids_sys_resetDecription: 'Auf Werkseinstellungen zurücksetzen.',
ids_sys_selectFilePrompt: 'Wählen Sie vor dem Hochladen eine Datei aus.',
ids_sys_restoreBackupWarn: 'Bei dieser Aktion werden die Einstellungen aktualisiert, und das Gerät wird nach beendetem Hochladen neugestartet. Möchten Sie fortfahren? ',
ids_sys_restoreFactoryWarn: 'Bei dieser Aktion werden die Werkseinstellungen wiederhergestellt, und das Gerät wird neugestartet. Möchten Sie fortfahren? ',
ids_sys_system: 'System',
ids_sys_rebootWarn: 'Möchten Sie das Gerät wirklich neustarten?',
ids_security_macFilterDescription: 'Geräte mit Zugriff auf das WLAN beschränken und WLAN-Sicherheit erhöhen.',
ids_security_macAddrInvalid: 'Ungültige MAC-Adresse.',
ids_security_macAddrNameWarn: 'Die MAC-Adresse ist bereits vorhanden.',
ids_security_addMacAddress: 'MAC-Adresse hinzufügen',
ids_sd_sdSharing: 'Freigabe der SD-Karte',
ids_sd_currentFolder: 'Aktueller Ordner',
ids_sd_dlna: 'DLNA                                 ',
ids_sd_close: 'Schließen',
ids_sd_serverName: 'Servername',
ids_sd_dlnaDes: 'Wenn Sie DLNA aktivieren, stehen die Medieninhalte auf der Speicherkarte auf dem verbundenen Gerät zur Verfügung.',
ids_sd_usedTotal: '(Genutzt/insgesamt)',
ids_sd_noSdCard: 'Keine Speicherkarte',
ids_sd_viewFile: 'Datei anzeigen',
ids_sd_sdShareMode: 'Modus Speicherkartenfreigabe',
ids_sd_sdCard: 'Speicherkarte',
ids_fota_checking: 'Überprüfung läuft…',
ids_fota_checkUpdate: 'Aktualisieren',
ids_fota_updateTitle: 'Systemaktualisierungen',
ids_fota_upgrading: 'Wird aktualisiert...',
ids_fota_upgradingTips: 'Schalten Sie das Gerät während der Aktualisierung nicht aus. Das Gerät startet nach der Aktualisierung neu.',
ids_fota_downloading: 'Wird heruntergeladen...',
ids_fota_batteryTips: 'Der Ladestand der Batterie ist zu gering. Das Gerät kann nicht upgedatet werden.　',
ids_fota_downloadError: 'Fehler beim Herunterladen',
ids_fota_findNewVersion: 'Neue Version suchen',
ids_fota_updateDescription: 'Wählen Sie Aktualisieren aus, um die neue Version zu installieren.',
ids_fota_latestVersion: 'Dies ist bereits die neueste Version',
ids_fota_haveNewVersion: 'Eine neue Software ist verfügbar. Aktualisieren Sie das Gerät.',
ids_more_onlineUpdate: 'Online-Update',
ids_sys_chooseFile:'Datei wählen',
ids_sys_noFileChosen:'Keine ausgewählt',
ids_sys_chooseFile:'Datei wählen',
ids_sys_noFileChosen:'Keine ausgewählt',
ids_tr069_client:'TR-069-Client – Konfiguration',
ids_tr069_tips:'Wählen Sie die gewünschten Werte aus und klicken Sie auf „Anwenden/Speichern“, um die TR-069-Clientoptionen zu konfigurieren.',
ids_tr069_inform:'Informieren',
ids_tr069_informInterval:'Informationsintervall',
ids_tr069_acsUrl:'ACS-URL',
ids_tr069_acsUsername:'ACS-Nutzername',
ids_tr069_acsPw:'ACS-Passwort',
ids_tr069_connRqAuth:'Authentifizierung für Verbindungs-Anfrage',
ids_tr069_connRqUsername:'Verbindungsanforderungs-Nutzername',
ids_tr069_connRqPw:'Verbindungsanforderungs-Passwort',
ids_tr069_inputInformInterval:'Bitte geben Sie vor dem Speichern das Zeitinterval für Benachrichtigungen ein.',
ids_tr069_inputAcsUrl:'Bitte geben Sie die ACS-URL ein, bevor Sie speichern.',
ids_tr069_inputAcsUserName:'Bitte geben Sie den ACS-Benutzernamen ein, bevor Sie speichern.',
ids_tr069_inputAcsPassword:'Bitte geben Sie das ACS-Passwort ein, bevor Sie speichern.',
ids_tr069_inputConReqUserName:'Bitte geben Sie den Benutzernamen für die Verbindungsanfrage ein, bevor Sie speichern.',
ids_tr069_inputConReqPassword:'Bitte geben Sie das Passwort für die Verbindungsanfrage ein, bevor Sie speichern.',
ids_tr069_informIntervalRule:'Das Zeitinterval für Benachrichtigungen soll zwischen 0 und 2678400 liegen, einschließlich „0123456789“ ',
ids_tr069_acsUrlRule:'Format der ACS-URL: z.B.: http://ip address:port/xxx',
ids_wifi_country:'Land',
ids_wifi_wlan_mode:'WLAN-Modus'
}