var resourceInfo={
ids_error: 'Erreur!',
ids_login: 'Connexion',
ids_auto: 'AUTO',
ids_automatic: 'Automatique',
ids_manual: 'Manuel',
ids_enable: 'Activer',
ids_validate: 'Valider',
ids_modify: 'Modifier',
ids_disable: 'Désactiver',
ids_subnetMask: 'Masque de sous-réseau',
ids_allow: 'Autoriser',
ids_deny: 'Refuser',
ids_day: 'jour',
ids_days: 'jours',
ids_hour: 'heure',
ids_hours: 'heures',
ids_minute: 'minute',
ids_minutes: 'minutes',
ids_requestError: 'Aucune réponse, l\'appareil a sans doute été déconnecté. Veuillez le redémarrer et recommencer.',
ids_success: 'Opération réussie!',
ids_fail: 'Échec!',
ids_back: 'Retour',
ids_icon_battery: 'Batterie',
ids_icon_timeElapsed: 'Temps écoulé',
ids_icon_debit: 'Débit',
ids_icon_people: 'Contacts',
ids_icon_downloaded: 'Téléchargements',
ids_icon_uploaded: 'Envois',
ids_menu_connection: 'Connexion',
ids_menu_sms: 'SMS',
ids_menu_settings: 'Réglages',
ids_menu_smsSettings: 'Réglages SMS',
ids_menu_connectDevice: 'Appareil connecté',
ids_menu_usage: 'Utilisation',
ids_menu_sharing: 'Partage',
ids_menu_usageSetting: 'Paramètres d’usage',
ids_menu_more: 'Autres',
ids_menu_language:'Langue',
ids_foot_copyright: 'Copyright 2014-2016 TCL Communication Ltd. TOUS DROITS RÉSERVÉS.',
ids_btn_help: 'Aide',
ids_btn_logout: 'Déconnex.',
ids_btn_block: 'Bloquer',
ids_btn_unblock: 'Débloquer',
ids_btn_apply: 'Appliquer',
ids_btn_cancel: 'Annuler',
ids_btn_next: 'Suivant',
ids_btn_continue: 'Continuer',
ids_btn_save: 'Enregistrer',
ids_btn_new: 'Nouveau',
ids_btn_edit: 'Modifier',
ids_btn_delete: 'Supprimer',
ids_btn_setDefault: 'Par&nbsp;défaut',
ids_btn_refresh: 'Actualiser',
ids_btn_select: 'Sélection',
ids_btn_reboot: 'Redémar.',
ids_btn_reset: 'Réinitialiser',
ids_btn_backup: 'sauvegarder',
ids_btn_restore: 'Restaurer',
ids_btn_ok: 'OK',
ids_btn_previous: 'Retour',
ids_btn_add: 'Ajouter',
ids_title_wps: 'WPS',
ids_title_advanced: 'Réglages avancés',
ids_title_blockDevice: 'Bloquer l’appareil',
ids_title_connectMode: 'Mode de connexion',
ids_title_networkMode: 'Mode réseau',
ids_title_macFilter: 'Filtre MAC',
ids_title_loginSettings: 'Paramètres de connexion',
ids_title_pinCodeSettings: 'Paramètres de code PIN',
ids_title_profilesManagement: 'Gestion des profils',
ids_title_wifiSettings: 'Paramètres Wi-Fi',
ids_title_about: 'À propos',
ids_title_tr069:'TR069',
ids_net_registing: 'Enregistrement…',
ids_net_select: 'Sélection du réseau',
ids_net_4gOnly: '4G uniquement',
ids_net_3gOnly: '3G uniquement',
ids_net_2gOnly: '2G uniquement',
ids_net_operator: 'Opérateur',
ids_net_noService: 'Aucun service',
ids_net_service: 'Service',
ids_net_status: 'État',
ids_net_searching: 'Recherche…',
ids_net_gsm: '2G',
ids_net_umts: '3G',
ids_net_lte: '4G',
ids_net_active: 'Actif',
ids_net_available: 'Disponible',
ids_net_forbid: 'Interdit',
ids_net_selectWarn: 'Sélectionnez un réseau !',
ids_sim_pinManagement: 'Gestion PIN',
ids_sim_remainTime: 'Essais restants',
ids_sim_pinCode: 'PIN',
ids_sim_pukCode: 'PUK',
ids_sim_simLockCode: 'Code blocage SIM',
ids_sim_newPinCode: 'Nouveau PIN',
ids_sim_confirmPinCode: 'Confirmer PIN',
ids_sim_lockForbidden: 'Verrouillage SIM interdit !',
ids_sim_noSimCard: 'Aucune carte SIM',
ids_sim_invalidSimCard: 'Carte SIM non valide',
ids_sim_pinNotAvailable: 'Code PIN non disponible.',
ids_sim_initializing: 'Initialisation SIM',
ids_sim_pinRequired: 'Code PIN obligatoire',
ids_sim_pukRequired: 'Code PUK obligatoire',
ids_sim_unknown: 'inconnu',
ids_sim_nck: 'NCK',
ids_sim_nsck: 'NSCK',
ids_sim_spck: 'SPCK',
ids_sim_cck: 'CCK',
ids_sim_pck: 'PCK',
ids_sim_rck: 'RCK',
ids_sim_simLocked: 'Blocage de la SIM obligatoire',
ids_sim_pinRequiredTips: 'Pour en savoir plus, cliquez sur « Code PIN obligatoire » pour déverrouiller.',
ids_sim_pukRequiredTips: 'Pour en savoir plus, cliquez sur « Code PUK obligatoire » pour déverrouiller.',
ids_sim_simLockedTips: 'Pour en savoir plus, cliquez sur « Blocage de la SIM obligatoire » pour déverrouiller.',
ids_sim_pinConfirmed: 'Le code PIN de confirmation doit être le même que le nouveau code PIN.',
ids_sim_pinRule: 'Le code PIN doit comporter entre 4 et 8 chiffres.',
ids_sim_pukRule: 'Le code PUK doit comporter 8 chiffres.',
ids_sim_newPinRule: 'Le nouveau code PIN doit comporter 4 à 8 chiffres.',
ids_sim_comfirmPinRule: 'La confirmation du code PIN doit comporter 4 à 8 chiffres.',
ids_sim_lockCodeRule: 'Le code de verrouillage SIM doit comporter 10 chiffres.',
ids_sim_pinEnable: 'La validation auto. du code PIN est activée.',
ids_sim_pinDisable: 'La validation auto. du code PIN est désactivée.',
ids_sim_autoPinState: 'Etat actuel',
ids_sim_autoValidate: 'Saisie automatique',
ids_sim_pinCodeOperation: 'Opération de code PIN',
ids_sim_pinError: 'Erreur de code PIN !',
ids_sim_changePinError: 'Erreur de changement du code PIN !',
ids_sim_pukError: 'Erreur du code PUK !',
ids_sim_simlockError: 'Erreur de blocage de la SIM !',
ids_sim_autoPin: 'Validation auto du code PIN',
ids_sim_autoPinError: 'Erreur de vérification auto. du code PIN !',
ids_profile_password: 'Mot de passe',
ids_profile_profileName: 'Nom du profil',
ids_profile_userName: 'Nom d\'utilisateur',
ids_profile_apn: 'Nom du point d\'accès',
ids_profile_protocal: 'Protocole',
ids_profile_deleteWarn: 'Supprimer profils?',
ids_profile_inputName: 'Saisissez le nom de profil avant d\'enregistrer ses réglages.',
ids_profile_profileNameRule: 'Le nom de profil ne peut pas comporter plus de 31 caractères, ni les caractères suivants:  , " : ; \\ & % + < > ?.',
ids_profile_userNameRule: 'Le nom d\'utilisateur ne peut pas comporter plus de 31 caractères, ni les caractères suivants:  , " : ; & \\.',
ids_profile_inputDialNum: 'Indiquez le numéro du profil !',
ids_profile_inputApn: 'Indiquez le nom du point d\'accès !',
ids_profile_numRule: 'Remarque: vous pouvez créer jusqu\'à 15 profils.',
ids_profile_dialNumber: 'Numéro du profil',
ids_profile_inputRule: 'La clé APN & Numéro du profil doit comporter entre 32 et 127 caractères ASCII, à l\'exception de: , " : ; & \\.',
ids_profile_pwdRule: 'Le mot de passe ne peut pas comporter plus de 31 caractères, ni les caractères suivants :  , " : ; & \\.',
ids_profile_nameWarn: 'Ce nom de profil existe déjà.',
ids_usage_duration: 'Durée',
ids_usage_clearHistory: 'Voulez-vous réinitialiser toutes les statistiques ?',
ids_usage_clear: 'Effacer l’historique',
ids_usage_home: 'Accueil',
ids_usage_roaming: 'Itinérance',
ids_usage_of: 'sur',
ids_usage_billingDay: 'Jour de facturation',
ids_usage_monthlyDataPlan: 'Forfait données mensuel',
ids_usage_dataConsumption: 'Consommation des données',
ids_usage_day: 'jour',
ids_usage_timeLimit: 'Durée max.',
ids_usage_setTimeLimit: 'Indiquer la durée max.',
ids_usage_minutesTimes: 'min.',
ids_usage_hrs: 'h',
ids_usage_timePassed: 'Durée passée',
ids_usage_autoDisconnected: 'Déconnexion automatique',
ids_usage_dataUsageReach: 'La consommation de données a atteint le plafond mensuel',
ids_usage_hours: 'heures',
ids_usage_minutes: 'minutes',
ids_usage_billingTimeTips: 'Veuillez saisir un jour entre 1 et 31.',
ids_usage_mothlyDataTips: 'Forfait données mensuel, compris entre 1 et 1024.',
ids_usage_startTimeTips: 'Forfait données mensuel, compris entre  1 et 43200.',
ids_wifi_offRule: 'Le Wifi a été désactivé suite à une longue période d\'inutilisation. Veuillez  réactiver manuellement en appuyant sur n\'importe quel bouton.',
ids_wifi_wifi: 'Wi-Fi',
ids_wifi_on: 'Activé',
ids_wifi_off: 'Désactivé',
ids_wifi_ssidBroadcast: 'Diffusion SSID',
ids_wifi_securityDisableDes: 'La désactivation annule la touche Wi-Fi.',
ids_wifi_cipher: 'Type de chiffrement',
ids_wifi_wpaTkip: 'TKIP',
ids_wifi_wpaAes: 'AES',
ids_wifi_showPwd: 'Afficher le mot de passe',
ids_wifi_wpa: 'WPA PSK',
ids_wifi_wpa2: 'WPA2 PSK',
ids_wifi_wepDescription: 'La clé WEP doit comporter 5 ou 13 caractères ASCII, ou 10 ou 26 chiffres hexadécimaux.',
ids_wifi_wpaDescription: 'La clé pré-partagée WPA (PSK) doit comporter entre 8 et 63 caractères ASCII ou 64 caractères hexadécimaux.',
ids_wifi_wpaRule: 'La clé WPA PSK doit comporter entre 32 et 127 caractères ASCII, à l\'exception de: " : ; & \\.',
ids_wifi_wepRule: 'La clé WEP doit se composer de caractères ASCII allant de 32 à 127, sauf pour: " : ; & \\.',
ids_wifi_disconWarning: 'La connexion Wi-Fi va être interrompue. Voulez-vous tout de même continuer ?',
ids_wifi_maxSsid: 'Le SSID doit se limiter à 32 caractères, de 0 à 9, de a à z, de A à Z et aux caractères « - », « _ », « . » et l’espace.',
ids_wifi_inputSsid: 'Indiquez le SSID.',
ids_wifi_wep: 'WEP',
ids_wifi_wpaWpa2Psk: 'WPA/WPA2 PSK',
ids_wifi_wepOpen: 'WEP-OPEN',
ids_wifi_wepShare: 'WEP-Shared',
ids_wifi_wpsActiveWarn: 'Procédure WPS en cours. Patientez 2 minutes, puis essayez à nouveau.',
ids_wifi_ssid2: 'SSID2.4GHz',
ids_wifi_cannotSet: 'La fonction Wi-Fi est désactivée. Cette option ne peut pas être traitée.',
ids_wifi_wifiSecurity: 'Wi-Fi Sécurité',
ids_wifi_apIsotation: 'Isolement de PA',
ids_wifi_802mode: 'Mode 802.11',
ids_wifi_channel: 'Canal Wi-Fi',
ids_wifi_maxUser: 'Nb max. d\'utilisateurs',
ids_wifi_encryption: 'Cryptage',
ids_wifi_key: 'Touche',
ids_wifi_pbc: 'PBC',
ids_wifi_pbcConfiguration: 'Push Button Configuration',
ids_wifi_wpsPin: 'PIN WPS',
ids_wifi_pbcDecription: '1. Appuyez sur le bouton WPS de l’appareil jusqu’à ce que ce dernier affiche WPS.<br/>2. Sur l’appareil (ex. : un PC), ouvrez le programme d’accès Wi-Fi, puis sélectionnez le PBC.<br/>3. cliquez sur l’icône en haut de l’écran.',
ids_wifi_pinDecription: 'PIN:<br/>1. Sur l’autre équipement (par exemple, l’ordinateur), sélectionnez l’utilitaire d’accès Wi-Fi qui permet d’activer le standard WPS (fourni par le constructeur de l’ordinateur), puis sélectionnez la méthode PIN. Un code PIN à 4 et 8 chiffres est alors généré;<br/>2. Activez le code PIN et saisissez le code PIN à 4 et 8 chiffres;<br/>3. Cliquez sur &lt;Appliquer&gt;.',
ids_wifi_wpsActive: 'WPS actif.',
ids_wifi_wpsPinRule: 'Le code PIN WPS doit comporter entre 4 et 8 caractères.',
ids_wifi_notSuppotWepWpa: 'WPS indisponible sous TKIP WEP, WPA, WPA2 !',
ids_wifi_notSuppotMacFilter: 'La procédure WPS (version 2.0) ne peut être activé si le filtre de l\'adresse MAC est activée.',
ids_wifi_offTip:'La connexion wifi est désactivée, veuillez l\'activer.',
ids_wifi_wpsNotSuppotSSIDHidden: 'Réseau (SSID) caché, impossible d\'activer le WPS.',
ids_login_loginPwd: 'Mot de passe de connexion',
ids_login_newPwd: 'Nouveau mot de passe',
ids_login_confirmPwdRule: 'Le nouveau mot de passe et le mot de passe de confirmation doivent être identiques.',
ids_login_inputCurrPwd: 'Le mot de passe est incorrect.',
ids_login_wrongPwd: 'Mauvais Mot de Passe',
ids_login_otherLogin: 'Un administrateur est deja connecté, Essayez plus tard.',
ids_login_timeuseout: 'Le temps de connexion a expiré, veuillez redémarrer et réessayer.',
ids_login_inputOldPwd: 'Saisissez l’ancien mot de passe.',
ids_login_inputNewPwd: 'Saisissez le nouveau mot de passe.',
ids_login_inputConfirmPwd: 'Immettere la password di conferma.',
ids_login_checkPwdRule: 'Password non valida. La password di accesso deve contenere 4-16 caratteri, compresi 0-9, a-z, A-Z e i caratteri speciali "-+!@$#^&*". Ripetere l',
ids_login_inputPwd: 'Saisissez le mot de passe.',
ids_login_nameOrPwdWrong: 'Le nom d’utilisateur ou le mot de passe est incorrect !',
ids_login_confirmPwd: 'Confirmation ',
ids_router_homeAddr: 'Adresse personnelle',
ids_ipAddress: 'Adresse IP',
ids_router_dhcpServer: 'Serveur DHCP',
ids_router_leaseTime: 'Durée de bail DHCP',
ids_router_restartWarn: 'Votre appareil devra être redémarré. Voulez-vous vraiment continuer ?',
ids_router_ipAddrEmpty: 'L\'adresse IP est vide. Veuillez réessayer !',
ids_router_ipAddrInvalid: 'L\'adresse IP est non valide. Veuillez réessayer !',
ids_router_subnetEmpty: 'Le masque de sous-réseau est vide. Veuillez réessayer !',
ids_router_subnetInvalid: 'Le masque de sous-réseau est non valide. Veuillez réessayer !',
ids_router_startIpInvalid: 'L\'adresse IP de début est non valide. Veuillez réessayer !',
ids_router_startIpEmpty: 'L\'adresse IP de début est vide. Veuillez réessayer !',
ids_router_endIpInvalid: 'L\'adresse IP de fin est non valide. Veuillez réessayer !',
ids_router_endIpEmpty: 'L\'adresse IP de fin est vide. Veuillez réessayer !',
ids_router_startSameSubnet: 'L\'adresse IP de début et l\'adresse IP doivent appartenir au même sous-réseau.',
ids_router_endSameSubnet: 'L\'adresse IP de fin et l\'adresse IP doivent appartenir au même sous-réseau.',
ids_router_endGeaterStart: 'L\'adresse IP de fin doit être supérieure à l\'adresse IP de début.',
ids_router_startIP: 'IP de début',
ids_router_endIP: 'IP de fin',
ids_router_ipRule: 'Erreur ! L\'adresse IP ne peut pas se terminer par le chiffre 10 car ce nombre est pré-réservé par le système et ne peut être inclut au pool des adresse IP DHCP.',
ids_sms_saveMode: 'Mode d\'enregistrement',
ids_sms_sendingPrompt: 'Envoi en cours..., veuillez patienter !',
ids_sms_inputNum: 'Indiquez le numéro de portable.',
ids_sms_mobileNumRule: 'Le numéro du portable doit se limiter à 20 caractères, code international compris, par exemple, « +0123456789 ». Recomposez-le.',
ids_sms_deleteWarning: 'Supprimer SMS?',
ids_sms_saveDevice: 'Appareil',
ids_sms_saveSimCard: 'carte SIM',
ids_sms_smsFull: 'La boîte aux SMS est pleine. Supprimez-en pour pouvoir en envoyer/enregistrer des nouveaux.',
ids_sms_selectSomeOptions: '3 contacts maximum',
ids_sms_selectAnOption: 'Sélectionner une option',
ids_sms_chatInputConfirm: 'Appuyer sur Entrée ou tapez « ; » pour terminer',
ids_sms_phoneNumberInvalid: 'Numéro de téléphone non valide',
ids_sms_draft: 'Brouillons',
ids_sms_saveDraftSuccess: 'SMS enregistré dans les brouillons',
ids_sms_saveDraftFailed: 'Échec de la sauvegarde du brouillon',
ids_sms_newMessageOn: 'non lu de',
ids_sms_messageSending: 'Un SMS est en cours d’envoi',
ids_sms_newMessage: 'Nouveau message',
ids_sms_deleteAll: 'Tout supprimer',
ids_sms_centerNum: 'Centre des SMS',
ids_sms_report: 'rapport SMS',
ids_sms_emptyMessageWarn: 'Le message est vide. Voulez-vous envoyer ce message vide ?',
ids_sms_numberWarning: 'Le texte saisi est trop long. Veuillez raccourcir.',
ids_sms_sendFail: 'Échec d’envoi du SMS !',
ids_sms_delivered: 'Envoyé',
ids_wan_connected: 'Connecté',
ids_wan_connecting: 'Connexion…',
ids_wan_disconnected: 'Déconnecter',
ids_wan_disconnecting: 'Déconnexion…',
ids_wan_tips: 'Erreur ! Mémoire pleine , vous pouvez réinitialiser le plan data mensuel et vous reconnecter.',
ids_wan_roamingAutoConnect: 'Connexion automatique à l\'étranger',
ids_wan_inputDeviceName: 'Attribuez un nom à l’appareil.',
ids_wan_connectIPMode: 'Mode de connexion IP',
ids_wan_cannotBlock: 'Le filtre MAC est activé, cette option ne peut être utilisée.',
ids_wan_Block: 'La liste d\'adresses MAC est pleine, cette option ne peut être utilisée.',
ids_sys_ipAddress: 'Adresse IP',
ids_sys_swVersion: 'Version logicielle',
ids_sys_hwVersion: 'Version matérielle',
ids_sys_imei: 'IMEI',
ids_sys_deviceName: 'Nom de l\'appareil',
ids_sys_macAddress: 'Adresse MAC',
ids_sys_rebootDecription: 'Cliquez sur ce bouton pour redémarrer l\'appareil.',
ids_sys_backupDecription: 'Télécharger (sauvegarder) la configuration.',
ids_sys_setRebootEvent: 'Cet appareil est en train de redémarrer. Patientez pendant 60 secondes avant de reconnectez-vous à l\'appareil Wi-Fi.',
ids_sys_resetDecription: 'Restaurer les réglages par défaut.',
ids_sys_selectFilePrompt: 'Sélectionnez un fichier avant le chargement.',
ids_sys_restoreBackupWarn: 'Une fois le chargement terminé, les réglages seront mis à jour et l\'appareil redémarré. Voulez-vous vraiment continuer ?',
ids_sys_restoreFactoryWarn: 'Les réglages usines seront restaurés et l\'appareil redémarré. Voulez-vous vraiment continuer ?',
ids_sys_system: 'système',
ids_sys_rebootWarn: 'Voulez-vous vraiment redémarrer cet appareil ?',
ids_security_macFilterDescription: 'Contrôle et gestion de l\'appareil accédant au réseau local sans fil et amélioration de la sécurité.',
ids_security_macAddrInvalid: 'Adresse MAC non valide.',
ids_security_macAddrNameWarn: 'L\'adresse MAC existe déjà.',
ids_security_addMacAddress: 'Ajouter l’adresse MAC',
ids_sd_sdSharing: 'Partage carte SD',
ids_sd_currentFolder: 'Dossier actif',
ids_sd_dlna: 'DLNA',
ids_sd_close: 'Fermer',
ids_sd_serverName: 'Nom du serveur',
ids_sd_dlnaDes: 'L’activation de la fonction DLNA met à disposition les fichiers multimédias sur la carte microSD à l’appareil connecté.',
ids_sd_usedTotal: '(Utilisé/Total)',
ids_sd_noSdCard: 'Carte SD absente',
ids_sd_viewFile: 'Afficher le fichier',
ids_sd_sdShareMode: 'Accès au contenus de la carte SD',
ids_sd_sdCard: 'Carte SD',
ids_fota_checking: 'Vérification…',
ids_fota_checkUpdate: 'Mettre à jour',
ids_fota_updateTitle: 'Mises à jour du système',
ids_fota_upgrading: 'Mise à niveau…',
ids_fota_upgradingTips: 'N’éteignez pas pendant la mise à niveau. L’appareil redémarrera après l’opération.',
ids_fota_downloading: 'Téléchargement …',
ids_fota_batteryTips: 'La batterie est basse, l’équipement ne pourra pas être mis à jour.',
ids_fota_downloadError: 'Erreur de téléchargement',
ids_fota_findNewVersion: 'Rechercher nouvelle version',
ids_fota_updateDescription: 'cliquez sur « Mettre à jour » pour installer la nouvelle version.',
ids_fota_latestVersion: 'Il s’agit déjà de la dernière version.',
ids_fota_haveNewVersion: 'Une nouvelle version est disponible. Cliquez sur Mettre à jour.',
ids_more_onlineUpdate: 'Mise à jour en ligne',
ids_sys_chooseFile:'Sélectionner un fichier',
ids_sys_noFileChosen:'Aucun fichier sélectionné',
ids_tr069_client:'Client TR-069 – Configuration',
ids_tr069_tips:'Sélectionnez les valeurs de votre choix, puis cliquez sur « Appliquer/Enregistrer » pour configurer les options du client TR-069.',
ids_tr069_inform:'Informer',
ids_tr069_informInterval:'Intervalle d’information',
ids_tr069_acsUrl:'URL de l’ACS',
ids_tr069_acsUsername:'Nom d’utilisateur ACS',
ids_tr069_acsPw:'Mot de passe ACS',
ids_tr069_connRqAuth:'Authentification de la demande de connexion',
ids_tr069_connRqUsername:'Nom d’utilisateur de la demande de connexion',
ids_tr069_connRqPw:'Mot de passe de la demande de connexion',
ids_tr069_inputInformInterval:'Saisissez l’intervalle d’état avant de l’enregistrer.',
ids_tr069_inputAcsUrl:'Saisissez l’URL de l’ACS avant de l’enregistrer.',
ids_tr069_inputAcsUserName:'Saisissez le nom d’utilisateur de l’ACS avant de l’enregistrer.',
ids_tr069_inputAcsPassword:'Saisissez le mot de passe de l’ACS avant de l’enregistrer.',
ids_tr069_inputConReqUserName:'Saisissez le nom d’utilisateur de la demande de connexion avant de l’enregistrer.',
ids_tr069_inputConReqPassword:'Saisissez le mot de passe pour la demande de connexion avant de l’enregistrer.',
ids_tr069_informIntervalRule:'L’intervalle d’état doit être numérique, de 0 à 2 678 400, ne comportant que les chiffres 0123456789.',
ids_tr069_acsUrlRule:'Format de l’URL de l’ACS : http://adresse IP:port/xxx',
ids_wifi_country:'Pays',
ids_wifi_wlan_mode:'Mode Wi-Fi'
}