var resourceInfo={
ids_error: 'Fout!',
ids_login: 'Aanmelden',
ids_auto: 'AUTO',
ids_automatic: 'Automatisch',
ids_manual: 'Handmatig',
ids_enable: 'Activeren',
ids_validate: 'Bevestigen',
ids_modify: 'Wijzigen',
ids_disable: 'Deactiveren',
ids_subnetMask: 'Subnet-masker',
ids_allow: 'Toestaan',
ids_deny: 'Afwijzen',
ids_day: 'dag',
ids_days: 'dagen',
ids_hour: 'uur',
ids_hours: 'uren',
ids_minute: 'minuut',
ids_minutes: 'minuten',
ids_requestError: 'Geen reactie. De verbinding met het apparaat kan zijn verbroken. Start het apparaat opnieuw op en probeer opnieuw.',
ids_success: 'Geslaagd!',
ids_fail: 'Mislukt!',
ids_back: 'Terug',
ids_icon_battery: 'Batterij',
ids_icon_timeElapsed: 'Tijd verstreken',
ids_icon_debit: 'Gebruikt',
ids_icon_people: 'Contacten',
ids_icon_downloaded: 'Download',
ids_icon_uploaded: 'Upload',
ids_menu_connection: 'Verbinding',
ids_menu_sms: 'SMS',
ids_menu_settings: 'Instellingen',
ids_menu_smsSettings: 'SMS Instellingen',
ids_menu_connectDevice: 'Verbonden Apparaten',
ids_menu_usage: 'Verbruik',
ids_menu_sharing: 'Delen',
ids_menu_usageSetting: 'Verbruik Instellingen',
ids_menu_more: 'Meer',
ids_menu_language: 'Taal',
ids_foot_copyright: 'Copyright 2014-2016 TCL Communication Ltd. Alle rechten voorbehouden.',
ids_btn_help: 'Help',
ids_btn_logout: 'Afmelden',
ids_btn_block: 'Blokkeren',
ids_btn_unblock: 'Deblokkeren',
ids_btn_apply: 'Toepassen',
ids_btn_cancel: 'Annuleren',
ids_btn_next: 'Verder',
ids_btn_continue: 'Doorgaan',
ids_btn_save: 'Opslaan',
ids_btn_new: 'Nieuw',
ids_btn_edit: 'Wijzigen',
ids_btn_delete: 'Wissen',
ids_btn_setDefault: 'Als Standaard',
ids_btn_refresh: 'Verversen',
ids_btn_select: 'Selecteren',
ids_btn_reboot: 'Herstarten',
ids_btn_reset: 'Reset',
ids_btn_backup: 'Back-up',
ids_btn_restore: 'Herstel',
ids_btn_ok: 'OK',
ids_btn_previous: 'Vorige',
ids_btn_add: 'Toevoegen',
ids_title_wps: 'WPS',
ids_title_advanced: 'Geavanceerde Instellingen',
ids_title_blockDevice: 'Apparaat blokkeren',
ids_title_connectMode: 'Verbinding-modus',
ids_title_networkMode: 'Netwerk-modus',
ids_title_macFilter: 'MAC-filter',
ids_title_loginSettings: 'Aanmeld Instellingen',
ids_title_pinCodeSettings: 'PIN-code Instellingen',
ids_title_profilesManagement: 'Profiel Beheer',
ids_title_wifiSettings: 'Wi-Fi Instellingen',
ids_title_about: 'Over',
ids_title_tr069: 'TR069',
ids_net_registing: 'Registreren......',
ids_net_select: 'Netwerk-selectie',
ids_net_4gOnly: 'Alleen 4G',
ids_net_3gOnly: 'Alleen 3G',
ids_net_2gOnly: 'Alleen 2G',
ids_net_operator: 'Operator',
ids_net_noService: 'Geen service',
ids_net_service: 'Service',
ids_net_status: 'Status',
ids_net_searching: 'Zoeken......',
ids_net_gsm: '2G',
ids_net_umts: '3G',
ids_net_lte: '4G',
ids_net_active: 'Actief',
ids_net_available: 'Beschikbaar',
ids_net_forbid: 'Verboden',
ids_net_selectWarn: 'Selecteer een netwerk!',
ids_sim_pinManagement: 'PIN-code Beheer',
ids_sim_remainTime: 'Poging(en) over',
ids_sim_pinCode: 'PIN-code',
ids_sim_pukCode: 'PUK-code',
ids_sim_simLockCode: 'SIM-lock-code',
ids_sim_newPinCode: 'Nieuwe PIN-code',
ids_sim_confirmPinCode: 'Bevestig PIN-code',
ids_sim_lockForbidden: 'SIM-lock is niet toegestaan!',
ids_sim_noSimCard: 'Geen SIM-kaart',
ids_sim_invalidSimCard: 'Ongeldige SIM-kaart',
ids_sim_pinNotAvailable: 'PIN-code is niet beschikbaar',
ids_sim_initializing: 'SIM initialiseren.',
ids_sim_pinRequired: 'PIN vereist',
ids_sim_pukRequired: 'PUK vereist',
ids_sim_unknown: 'Onbekend',
ids_sim_nck: 'NCK',
ids_sim_nsck: 'NSCK',
ids_sim_spck: 'SPCK',
ids_sim_cck: 'CCK',
ids_sim_pck: 'PCK',
ids_sim_rck: 'RCK',
ids_sim_simLocked: 'SIM-lock vereist',
ids_sim_pinRequiredTips: 'Voor meer informatie, klik op "PIN vereist" om te ontgrendelen.',
ids_sim_pukRequiredTips: 'Voor meer informatie, klik op "PUK vereist" om te ontgrendelen.',
ids_sim_simLockedTips: 'Voor meer informatie, klik op "SIM-lock vereist" om te ontgrendelen.',
ids_sim_pinConfirmed: 'De PIN-code ter bevestiging moet gelijk zijn aan de nieuwe PIN-code.',
ids_sim_pinRule: 'PIN-code moet 4-8 cijfers zijn.',
ids_sim_pukRule: 'PUK-code moet 8 cijfers zijn.',
ids_sim_newPinRule: 'Nieuwe PIN-code moet 4-8 cijfers zijn.',
ids_sim_comfirmPinRule: 'PIN-code ter bevestiging moet 4-8 cijfers zijn.',
ids_sim_lockCodeRule: 'SIM-lock-code moet 10 cijfers zijn.',
ids_sim_pinEnable: 'PIN autom. valideren is ingeschakeld.',
ids_sim_pinDisable: 'PIN autom. valideren is uitgeschakeld.',
ids_sim_autoPinState: 'Huidige status',
ids_sim_autoValidate: 'Automatisch valideren',
ids_sim_pinCodeOperation: 'PIN-code functie',
ids_sim_pinError: 'PIN-code fout',
ids_sim_changePinError: 'Fout bij wijzigen PIN-code!',
ids_sim_pukError: 'PUK-code fout',
ids_sim_simlockError: 'SIM-lock-code fout',
ids_sim_autoPin: 'PIN-code automatische valideren ',
ids_sim_autoPinError: 'Fout bij automatisch valideren PIN-code',
ids_profile_password: 'Wachtwoord',
ids_profile_profileName: 'Profielnaam',
ids_profile_userName: 'Gebruikersnaam',
ids_profile_apn: 'APN',
ids_profile_protocal: 'Protocol',
ids_profile_deleteWarn: 'Wilt u dit profiel verwijderen?',
ids_profile_inputName: 'Voer de profielnaam in, voordat u het profiel opslaat.',
ids_profile_profileNameRule: 'De maximum lengte van de profielnaam is 31 tekens, uitgezonderd:, " : ; \\ & % + < > ?',
ids_profile_userNameRule: 'De maximum lengte van de gebruikersnaam is 31 tekens, uitgezonderd:  " : ; & \\.',
ids_profile_inputDialNum: 'Voer het nummer in!',
ids_profile_inputApn: 'Voer de APN in!',
ids_profile_numRule: 'Opmerking: Het maximum aantal profielen dan u kunt aanmaken is 15.',
ids_profile_dialNumber: 'Nummer',
ids_profile_inputRule: 'APN & Nummer moet bestaan uit ASCII tekens in het bereik van 32-127, uitgezonderd: " : ; & \\.',
ids_profile_pwdRule: 'De maximum lengte van het wachtwoord is 31 tekens, uitgezonderd: " : ; & \\',
ids_profile_nameWarn: 'De profielnaam bestaat al.',
ids_usage_duration: 'Tijdsduur',
ids_usage_clearHistory: 'Wilt u alle statistieken op nul zetten?',
ids_usage_clear: 'Historie wissen',
ids_usage_home: 'Thuis',
ids_usage_roaming: 'Roaming',
ids_usage_of: 'van',
ids_usage_billingDay: 'Dag afrekening',
ids_usage_monthlyDataPlan: 'Maand Data-bundel',
ids_usage_dataConsumption: 'Data-gebruik',
ids_usage_day: 'dag',
ids_usage_timeLimit: 'Tijdslimiet',
ids_usage_setTimeLimit: 'Tijdslimiet instellen',
ids_usage_minutesTimes: 'min.',
ids_usage_hrs: 'Uur',
ids_usage_timePassed: 'Tijd verstreken',
ids_usage_autoDisconnected: 'Automatisch verbreken',
ids_usage_dataUsageReach: 'Wanneer data-gebruik de Maand Data-bundel heeft bereikt',
ids_usage_hours: 'uren',
ids_usage_minutes: 'minuten',
ids_usage_billingTimeTips: 'Voer de dag in tussen 1-31.',
ids_usage_mothlyDataTips: 'Voer een waarde in tussen 1-1024.',
ids_usage_startTimeTips: 'Voer een waarde in tussen 1-43200.',
ids_wifi_offRule: 'Wi-Fi is momenteel uitgeschakeld, omdat lange tijd geen client verbonden was. Schakel Wi-Fi handmatig in door een toets op het apparaat in te drukken, als u Wi-Fi wilt gebruiken.',
ids_wifi_wifi: 'Wi-Fi',
ids_wifi_on: 'Aan',
ids_wifi_off: 'Uit',
ids_wifi_ssidBroadcast: 'SSID Broadcast',
ids_wifi_securityDisableDes: 'Deactiveren betekent dat de beveiliging met Wi-Fi-sleutel wordt uitgeschakeld.',
ids_wifi_cipher: 'Versleutelingstype',
ids_wifi_wpaTkip: 'TKIP',
ids_wifi_wpaAes: 'AES',
ids_wifi_showPwd: 'Wachtwoord tonen',
ids_wifi_wpa: 'WPA PSK  ',
ids_wifi_wpa2: 'WPA2 PSK  ',
ids_wifi_wepDescription: 'WEP Key bestaat uit 5 of 13 ASCII tekens, of 10 of 26 hexadecimale digits.',
ids_wifi_wpaDescription: 'De WPA Pre-Shared Key (PSK) moet bestaan uit 8-63 ASCII tekens of 64 hexadecimale digits.',
ids_wifi_wpaRule: 'WPA PSK moet bestaan uit ASCII tekens in het bereik van 32-127, uitgezonderd: " : ; & \.',
ids_wifi_wepRule: 'WEP Key moet bestaan uit ASCII tekens in het bereik van 32-127, uitgezonderd: " : ; & \.',
ids_wifi_disconWarning: 'Deze actie zal Wi-Fi verbreken. Wilt u doorgaan?',
ids_wifi_maxSsid: 'De maximum lengte van SSID is 32 tekens, inclusief 0-9, a-z, A-Z, "-", "_", "." ," ".',
ids_wifi_inputSsid: 'Voer de SSID in.',
ids_wifi_wep: 'WEP',
ids_wifi_wpaWpa2Psk: 'WPA/WPA2 PSK',
ids_wifi_wepOpen: 'WEP-OPEN  ',
ids_wifi_wepShare: 'WEP-Shared',
ids_wifi_wpsActiveWarn: 'WPS-procedure is actief. Probeer het over 2 minuten opnieuw.',
ids_wifi_ssid2: 'SSID 2.4GHz',
ids_wifi_cannotSet: 'Wi-Fi is momenteel uitgeschakeld. Deze optie kan nu niet worden verwerkt.',
ids_wifi_wifiSecurity: 'Wi-Fi Beveiliging',
ids_wifi_apIsotation: 'AP Isolatie',
ids_wifi_802mode: '802.11 Modus',
ids_wifi_channel: 'Wi-Fi Kanaal',
ids_wifi_maxUser: 'Max aantal gebruikers',
ids_wifi_encryption: 'Versleuteling',
ids_wifi_key: 'Sleutel',
ids_wifi_pbc: 'PBC',
ids_wifi_pbcConfiguration: 'Push Button Configuratie',
ids_wifi_wpsPin: 'WPS PIN',
ids_wifi_pbcDecription: '1. Druk de WPS-knop op het apparaat in totdat WPS op het scherm verschijnt;<br/>2. Op het aan te sluiten apparaat (bijv. PC) opent u het Wi-Fi hulpprogramma en selecteert u PBC;<br/>3. Klik op het icoon boven.',
ids_wifi_pinDecription: 'PIN:<br/>1. Op het aan te sluiten apparaat (bijv. PC) opent u het Wi-Fi hulpprogramma en selecteert u PIN-methode. Er wordt dan een PIN-code van 4 of 8 cijfers gegenereerd;<br/>2. Activeer PIN en voer de PIN-code van 4 of 8 cijfers in;<br/>3. Klik op &lt;Toepassen&gt;.',
ids_wifi_wpsActive: 'WPS is geactiveerd.',
ids_wifi_wpsPinRule: 'WPS PIN-code moet 4 of 8 cijfers zijn.',
ids_wifi_notSuppotWepWpa: 'WPS is niet beschikbaar bij gebruik van WEP, WPA, WPA2 TKIP!',
ids_wifi_notSuppotMacFilter: 'WPS-procedure (versie 2.0) kan niet worden geactiveerd als MAC-adres filter is ingeschakeld.',
ids_wifi_offTip: 'Wi-Fi is uitgeschakeld. Probeer opnieuw nadat Wi-Fi is ingeschakeld.',
ids_wifi_wpsNotSuppotSSIDHidden: 'SSID afgescherm, WPS kan niet worden gebruikt.',
ids_login_loginPwd: 'Aanmeld wachtwoord',
ids_login_newPwd: 'Nieuw wachtwoord',
ids_login_confirmPwdRule: 'Het nieuwe wachtwoord en het wachtwoord ter bevestiging moeten gelijk zijn.',
ids_login_inputCurrPwd: 'Huidige wachtwoord is onjuist.',
ids_login_wrongPwd: 'Onjuist wachtwoord!',
ids_login_otherLogin: 'De administrator is reeds aangemeld. Probeer het later.',
ids_login_timeuseout: 'Maximum aantal pogingen om aan te melden bereikt. Herstart apparaat en probeer opnieuw.',
ids_login_inputOldPwd: 'Voer het oude wachtwoord in.',
ids_login_inputNewPwd: 'Voer het nieuwe wachtwoord in.',
ids_login_inputConfirmPwd: 'Voer het wachtwoord ter bevestiging in.',
ids_login_checkPwdRule: 'Ongeldig wachtwoord! De lengte van het aanmeld wachtwoord is 4-16 tekens, inclusief 0-9, a-z, A-Z,"-+!@$#^&*", voer opnieuw in.',
ids_login_inputPwd: 'Voer het wachtwoord in',
ids_login_nameOrPwdWrong: 'Gebruikersnaam of wachtwoord is onjuist.',
ids_login_confirmPwd: 'Bevestig wachtwoord',
ids_router_homeAddr: 'Thuis-adres',
ids_ipAddress:'IP-adres',
ids_router_dhcpServer: 'DHCP-server',
ids_router_leaseTime: 'DHCP IP Lease-tijd',
ids_router_restartWarn: 'Deze actie vereist dat het apparaat opnieuw wordt opgestart. Wilt u doorgaan?',
ids_router_ipAddrEmpty: 'IP-adres is leeg. Voer opnieuw in!',
ids_router_ipAddrInvalid: 'IP-adres is ongeldig. Voer opnieuw in!',
ids_router_subnetEmpty: 'Subnet-masker is leeg. Voer opnieuw in!',
ids_router_subnetInvalid: 'Subnet-masker is ongeldig. Voer opnieuw in!',
ids_router_startIpInvalid: 'Start IP-adres is ongeldig. Voer opnieuw in!',
ids_router_startIpEmpty: 'Start IP-adres is leeg. Voer opnieuw in!',
ids_router_endIpInvalid: 'Eind IP-adres is ongeldig. Voer opnieuw in!',
ids_router_endIpEmpty: 'Eind IP-adres is leeg. Voer opnieuw in!',
ids_router_startSameSubnet: 'Start IP-adres en "IP-adres" moeten behoren tot hetzelfde subnet.',
ids_router_endSameSubnet: 'Eind IP-adres en "IP-adres" moeten behoren tot hetzelfde subnet.',
ids_router_endGeaterStart: 'Eind IP-adres moet hoger zijn dan "Start IP-adres".',
ids_router_startIP: 'Start IP-adres',
ids_router_endIP: 'Eind IP-adres',
ids_router_ipRule: 'Fout! Let op, 10 IP-adressen na het Thuis-adres zijn gereserveerd voor het systeem. Deze kunnen niet binnen de DHCP IP-pool worden gebruikt.  ',
ids_sms_saveMode: 'Opslag-modus',
ids_sms_sendingPrompt: 'Zenden......, even wachten!',
ids_sms_inputNum: 'Voer het mobiele nummer in.',
ids_sms_mobileNumRule: 'De maximum lengte van het mobiele nummer is 20 cijfers, bevattende "+0123456789". Voer opnieuw in.',
ids_sms_deleteWarning: 'Wilt u bericht(en) wissen?',
ids_sms_saveDevice: 'Apparaat',
ids_sms_saveSimCard: 'SIM-kaart',
ids_sms_smsFull: 'Het SMS postvak is vol. Wis een aantal SMS-en om een nieuwe SMS te kunnen verzenden/opslaan.',
ids_sms_selectSomeOptions: 'Maximaal 3 contacten',
ids_sms_selectAnOption: 'Selecteer een optie',
ids_sms_chatInputConfirm: 'Druk op Enter of voer ";" in om te voltooien.',
ids_sms_phoneNumberInvalid: 'Telefoonnummer ongeldig',
ids_sms_draft: 'Concepten',
ids_sms_saveDraftSuccess: 'SMS is opgeslagen als concept',
ids_sms_saveDraftFailed: 'Opslaan als concept mislukt',
ids_sms_newMessageOn: 'ongelezen van',
ids_sms_messageSending: 'Er wordt een SMS verzonden',
ids_sms_newMessage: 'Nieuw bericht',
ids_sms_deleteAll: 'Alles wissen',
ids_sms_centerNum: 'SMS-center',
ids_sms_report: 'SMS Afleverrapport',
ids_sms_emptyMessageWarn: 'Bericht is leeg. Wilt u dit lege bericht verzenden?',
ids_sms_numberWarning: 'De invoer is te lang. Wis een gedeelte.',
ids_sms_sendFail: 'SMS verzenden is mislukt!',
ids_wan_tips: 'Mislukt! Gebruikslimiet is overschreden. U kunt de Maand Data-bundel opnieuw instellen en weer verbinding maken.',
ids_sms_delivered: 'Afgeleverd',
ids_wan_connected: 'Verbonden',
ids_wan_connecting: 'Verbinden...... ',
ids_wan_disconnected: 'Verbroken',
ids_wan_disconnecting: 'Verbreken...... ',
ids_wan_roamingAutoConnect: 'Automatisch verbinding maken ook tijdens roaming',
ids_wan_inputDeviceName: 'Voer apparaatnaam in',
ids_wan_connectIPMode: 'Verbindings-IP-modus',
ids_wan_cannotBlock: 'MAC-filter staat nu op Toestaan. Deze optie kan niet uitgevoerd worden.',
ids_wan_Block: 'De lijst met MAC-adressen is vol. Deze optie kan niet uitgevoerd worden.',
ids_sys_ipAddress: 'IP-adres',
ids_sys_swVersion: 'Software versie',
ids_sys_hwVersion: 'Hardware versie',
ids_sys_imei: 'IMEI',
ids_sys_deviceName: 'Apparaatnaam',
ids_sys_macAddress: 'MAC-adres',
ids_sys_rebootDecription: 'Klik op deze knop om het apparaat opnieuw op te starten.',
ids_sys_backupDecription: 'Download (Back-up) de configuratie.',
ids_sys_setRebootEvent: 'Het apparaat wordt opnieuw opgestart.Wacht 60 seconden. Maak dan opnieuw verbinding met het Wi-Fi apparaat. ',
ids_sys_resetDecription: 'Fabrieksinstellingen herstellen.',
ids_sys_selectFilePrompt: 'Selecteer een bestand voor het uploaden.',
ids_sys_restoreBackupWarn: 'Deze actie zal de instellingen bijwerken. Het apparaat wordt opnieuw opgestart zodra de upload gereed is. Wilt u doorgaan?',
ids_sys_restoreFactoryWarn: 'Deze actie zal de fabrieksinstellingen herstellen en het apparaat wordt opnieuw opgestart. Wilt u doorgaan?',
ids_sys_system: 'Systeem ',
ids_sys_rebootWarn: 'Wilt u het apparaat opnieuw opstarten?',
ids_security_macFilterDescription: 'Controleer en beheer de apparatentoegang tot de WLAN. (Verbeter de beveiliging van WLAN).',
ids_security_macAddrInvalid: 'MAC-adres is ongeldig.',
ids_security_macAddrNameWarn: 'Het MAC-adres bestaat al.',
ids_security_addMacAddress: 'MAC-adres toevoegen',
ids_sd_sdSharing: 'SD-kaart delen',
ids_sd_currentFolder: 'Huidige Map',
ids_sd_dlna: 'DLNA',
ids_sd_close: 'Sluiten',
ids_sd_serverName: 'Servernaam',
ids_sd_dlnaDes: 'Inschakelen van DLNA maakt de media-inhoud op de microSD-kaart beschikbaar voor verbonden apparaten.',
ids_sd_usedTotal: '(Gebruikt/Totaal)',
ids_sd_noSdCard: 'Geen SD-kaart',
ids_sd_viewFile: 'Bestand bekijken',
ids_sd_sdShareMode: 'SD Delen-modus',
ids_sd_sdCard: 'SD-kaart',
ids_fota_checking: 'Controleren...',
ids_fota_checkUpdate: 'Updaten',
ids_fota_updateTitle: 'Systeemupdates',
ids_fota_upgrading: 'Updaten......',
ids_fota_upgradingTips: 'Schakel het apparaat niet uit tijdens het updaten. Het apparaat zal opnieuw opstarten na de update.',
ids_fota_downloading: 'Downloaden...',
ids_fota_batteryTips: 'Batterij is bijna leeg. Het apparaat kan niet worden geüpdate.',
ids_fota_downloadError: 'Download fout',
ids_fota_findNewVersion: 'Nieuw versie gevonden',
ids_fota_updateDescription: 'Klik op "Updaten" om te updaten naar de nieuwe versie.',
ids_fota_latestVersion: 'Deze software is al de laatste versie.',
ids_fota_haveNewVersion: 'Een nieuwe software is beschikbaar. Klik om te updaten.',
ids_more_onlineUpdate: 'On-line Update',
ids_sys_chooseFile: 'Bestand selecteren',
ids_sys_noFileChosen: 'Geen bestand geselecteerd',
ids_tr069_client: 'TR-069-client – Configuratie',
ids_tr069_tips: 'Selecteer de gewenste waarden en klik op "Toepassen/Opslaan" om de TR-069-client opties te configureren.',
ids_tr069_inform: 'Informeren',
ids_tr069_informInterval: 'Informatie-interval (s)',
ids_tr069_acsUrl: 'ACS URL',
ids_tr069_acsUsername: 'ACS Gebruikersnaam',
ids_tr069_acsPw: 'ACS Wachtwoord',
ids_tr069_connRqAuth: 'Verbindingsverzoek Authenticatie',
ids_tr069_connRqUsername: 'Verbindingsverzoek Gebruikersnaam',
ids_tr069_connRqPw: 'Verbindingsverzoek Wachtwoord',
ids_tr069_inputInformInterval: 'Voer de informatie-interval in voordat u deze opslaat.',
ids_tr069_inputAcsUrl: 'Voer de acs url in voordat u deze opslaat.',
ids_tr069_inputAcsUserName: 'Voer de acs gebruikersnaam in voordat u deze opslaat.',
ids_tr069_inputAcsPassword: 'Voer het acs wachtwoord in voordat u deze opslaat.',
ids_tr069_inputConReqUserName: 'Voer de verbindingsverzoek gebruikersnaam in voordat u deze opslaat.',
ids_tr069_inputConReqPassword: 'Voer het verbindingsverzoek wachtwoord in voordat u deze opslaat.',
ids_tr069_informIntervalRule: 'Informatie-interval moet liggen tussen 0-2678400, bevattende "0123456789".',
ids_tr069_acsUrlRule: 'Acs url formaat: bijv.: http://ip-adres:poort/xxx',
ids_wifi_wlan_mode:'Wlan-modus',
ids_wifi_country:'Land'
}