var resourceInfo={
ids_error: 'Errore!',
ids_login: 'Accedi',
ids_auto: 'AUTO',
ids_automatic: 'Automatica',
ids_manual: 'Manuale',
ids_enable: 'Abilita',
ids_validate: 'Convalida',
ids_modify: 'Modifica',
ids_disable: 'Disabilita',
ids_subnetMask: 'Subnet mask',
ids_allow: 'Consenti',
ids_deny: 'Rifiuta',
ids_day: 'giorno',
ids_days: 'giorni ',
ids_hour: 'ora',
ids_hours: 'ore',
ids_minute: 'minuto',
ids_minutes: 'minuti ',
ids_requestError: 'Nessuna risposta. Il dispositivo potrebbe non essere connesso. Riavviare il dispositivo e riprovare.',
ids_success: 'Operazione completata!',
ids_fail: 'Operazione non riuscita!',
ids_back: 'Indietro',
ids_icon_battery: 'Batteria',
ids_icon_timeElapsed: 'Tempo trascorso',
ids_icon_debit: 'Addebita',
ids_icon_people: 'Persone',
ids_icon_downloaded: 'Scaricati',
ids_icon_uploaded: 'Caricati',
ids_menu_connection: 'Connessione',
ids_menu_sms: 'SMS',
ids_menu_settings: 'Impostazioni',
ids_menu_smsSettings: 'Impostazioni SMS',
ids_menu_connectDevice: 'Dispositivo connesso',
ids_menu_usage: 'Utilizzo',
ids_menu_sharing: 'Condivisione',
ids_menu_usageSetting: 'Impostazioni utilizzo',
ids_menu_more: 'Altro',
ids_menu_language:'Lingua',
ids_foot_copyright: 'Copyright 2014-2016 TCL Communication Ltd. Tutti i diritti riservati.',
ids_btn_help: 'Guida',
ids_btn_logout: 'Disconnetti',
ids_btn_block: 'Blocca',
ids_btn_unblock: 'Sblocca',
ids_btn_apply: 'Applica',
ids_btn_cancel: 'Annulla',
ids_btn_next: 'Successivo',
ids_btn_continue: 'Continua',
ids_btn_save: 'Salva',
ids_btn_new: 'Nuovo',
ids_btn_edit: 'Modifica',
ids_btn_delete: 'Elimina',
ids_btn_setDefault: 'Imp.&nbsp;predef. ',
ids_btn_refresh: 'Aggiorna',
ids_btn_select: 'Seleziona',
ids_btn_reboot: 'Riavvia',
ids_btn_reset: 'Reimposta ',
ids_btn_backup: 'esegui',
ids_btn_restore: 'ripristina',
ids_btn_ok: 'OK',
ids_btn_previous: 'Precedente',
ids_btn_add: 'Aggiungi',
ids_title_wps: 'WPS',
ids_title_advanced: 'Impostazione avanzata',
ids_title_blockDevice: 'Blocca dispositivo',
ids_title_connectMode: 'Modalità di connessione',
ids_title_networkMode: 'Modalità rete',
ids_title_macFilter: 'Filtro MAC ',
ids_title_loginSettings: 'Impostazioni accesso',
ids_title_pinCodeSettings: 'Impostazioni codice PIN',
ids_title_profilesManagement: 'Gestione profili',
ids_title_wifiSettings: 'Impostazioni Wi-Fi',
ids_title_about: 'Informazioni',
ids_title_tr069:'TR069',
ids_net_registing: 'Registrazione in corso…',
ids_net_select: 'Selezione rete',
ids_net_4gOnly: 'Solo 4G',
ids_net_3gOnly: 'Solo 3G',
ids_net_2gOnly: 'Solo 2G',
ids_net_operator: 'Operatore',
ids_net_noService: 'Nessun servizio',
ids_net_service: 'Servizio',
ids_net_status: 'Stato',
ids_net_searching: 'Ricerca in corso…',
ids_net_gsm: '2G',
ids_net_umts: '3G',
ids_net_lte: '4G',
ids_net_active: 'Attivo ',
ids_net_available: 'Disponibile',
ids_net_forbid: 'Non consentito',
ids_net_selectWarn: 'Selezionare una rete. ',
ids_sim_pinManagement: 'Gestione PIN',
ids_sim_remainTime: 'Tempo residuo',
ids_sim_pinCode: 'PIN',
ids_sim_pukCode: 'PUK',
ids_sim_simLockCode: 'Codice blocco SIM',
ids_sim_newPinCode: 'Nuovo PIN',
ids_sim_confirmPinCode: 'Conferma PIN',
ids_sim_lockForbidden: 'Blocco Sim non consentito.',
ids_sim_noSimCard: 'Nessuna scheda SIM',
ids_sim_invalidSimCard: 'Scheda SIM non valida',
ids_sim_pinNotAvailable: 'Codice PIN non disponibile.',
ids_sim_initializing: 'Inizializzazione SIM ',
ids_sim_pinRequired: 'PIN necessario',
ids_sim_pukRequired: 'PUK necessario',
ids_sim_unknown: 'sconosciuto',
ids_sim_nck: 'NCK',
ids_sim_nsck: 'NSCK',
ids_sim_spck: 'SPCK',
ids_sim_cck: 'CCK',
ids_sim_pck: 'PCK',
ids_sim_rck: 'RCK',
ids_sim_simLocked: 'Blocco SIM necessario',
ids_sim_pinRequiredTips: 'Per ulteriori informazioni, prima fare clic su "PIN necessario" per sbloccare.',
ids_sim_pukRequiredTips: 'Per ulteriori informazioni, prima fare clic su "PUK necessario" per sbloccare.',
ids_sim_simLockedTips: 'Per ulteriori informazioni, prima fare clic su "Blocco SIM necessario" per sbloccare.',
ids_sim_pinConfirmed: 'Il codice PIN di conferma deve corrispondere al nuovo codice PIN.',
ids_sim_pinRule: 'Il codice PIN deve essere compreso tra 4 e 8 cifre.',
ids_sim_pukRule: 'Il codice PUK deve essere composto da 8 cifre.',
ids_sim_newPinRule: 'Il nuovo codice PIN deve essere composto da 4-8 cifre.',
ids_sim_comfirmPinRule: 'Il codice PIN di conferma deve essere composto da 4-8 cifre.',
ids_sim_lockCodeRule: 'Il codice SIM Lock deve essere composto da 10 cifre.',
ids_sim_pinEnable: 'Convalida automatica PIN attivata.',
ids_sim_pinDisable: 'Convalida automatica PIN disattivata.',
ids_sim_autoPinState: 'Stato corrente',
ids_sim_autoValidate: 'Validazione automatica',
ids_sim_pinCodeOperation: 'Operazione codice PIN',
ids_sim_pinError: 'Errore PIN.',
ids_sim_changePinError: 'Cambia errore PIN.',
ids_sim_pukError: 'Errore PUK.',
ids_sim_simlockError: 'Errore blocco SIM.',
ids_sim_autoPin: 'Convalida automatica codice PIN',
ids_sim_autoPinError: 'Errore verifica automatica PIN.',
ids_profile_password: 'Password',
ids_profile_profileName: 'Nome profilo',
ids_profile_userName: 'Nome utente',
ids_profile_apn: 'APN',
ids_profile_protocal: 'Protocollo',
ids_profile_deleteWarn: 'Confermate di volerlo cancellare?',
ids_profile_inputName: 'Immettere il nome del profilo prima di salvare le impostazioni del profilo.',
ids_profile_profileNameRule: 'La lunghezza massima del nome profilo è 31 caratteri, ad eccezione di: , " : ; \\ & % + < > ?.',
ids_profile_userNameRule: 'La lunghezza massima del nome utente è 31 caratteri, ad eccezione di: , " : ; & \\.',
ids_profile_inputDialNum: 'Immettere il numero del profilo.',
ids_profile_inputApn: 'Immettere l\'APN.',
ids_profile_numRule: 'Nota: il numero massimo di profili che è possibile creare è 15.',
ids_profile_dialNumber: 'Numero del profilo',
ids_profile_inputRule: 'APN & Numero del profilo deve contenere caratteri ASCII compresi tra 32 e 127, ad eccezione di: , " : ; & \\.',
ids_profile_pwdRule: 'La lunghezza massima della password è 31 caratteri, ad eccezione di: , " : ; & \\.',
ids_profile_nameWarn: 'Nome profilo già esistente.',
ids_usage_duration: 'Durata',
ids_usage_clearHistory: 'Reimpostare tutte le statistiche?',
ids_usage_clear: 'Cancella cronologia',
ids_usage_home: 'Home',
ids_usage_roaming: 'Roaming',
ids_usage_of: 'di',
ids_usage_billingDay: 'Giorno fatturazione',
ids_usage_monthlyDataPlan: 'Programma dati mensili',
ids_usage_dataConsumption: 'Consumo dati',
ids_usage_day: 'giorno',
ids_usage_timeLimit: 'Limite orario',
ids_usage_setTimeLimit: 'Imposta limite orario',
ids_usage_minutesTimes: 'min.',
ids_usage_hrs: 'Hrs',
ids_usage_timePassed: 'Tempo trascorso',
ids_usage_autoDisconnected: 'Disconnessione automatica',
ids_usage_dataUsageReach: 'Quando il traffico dati raggiunge il tetto mensile',
ids_usage_hours: 'ore',
ids_usage_minutes: 'minuti ',
ids_usage_billingTimeTips: 'Immettere il giorno compreso tra 1-31.',
ids_usage_mothlyDataTips: 'Immettere i dati compresi tra 1-1024.',
ids_usage_startTimeTips: 'Immettere i dati compresi tra 1-43200.',
ids_wifi_offRule: 'WIFI al momento disabilitato dal momento che nessun client si è connesso per lungo tempo. Abilitare manualmente il WIFI premendo un tasto del dispositivo per utilizzarlo.',
ids_wifi_wifi: 'Wi-Fi',
ids_wifi_on: 'Attivato',
ids_wifi_off: 'Disattivato',
ids_wifi_ssidBroadcast: 'Trasmissione SSID',
ids_wifi_securityDisableDes: 'Per "Disattivare" si intende annullare la chiave Wi-Fi.',
ids_wifi_cipher: 'Tipo di crittografia',
ids_wifi_wpaTkip: 'TKIP',
ids_wifi_wpaAes: 'AES',
ids_wifi_showPwd: 'Mostra password',
ids_wifi_wpa: 'WPA-PSK',
ids_wifi_wpa2: 'WPA2-PSK ',
ids_wifi_wepDescription: 'La chiave WEP è composta da 5 o 13 caratteri ASCII oppure da 10 o 26 cifre esadecimali.',
ids_wifi_wpaDescription: 'La chiave WPA-PSK (Pre-Shared Key) deve contenere tra 8 e 63 caratteri ASCII o 64 cifre esadecimali.',
ids_wifi_wpaRule: 'WPA PSK deve contenere caratteri ASCII compresi tra 32 e 127, ad eccezione di: , " : ; & \\',
ids_wifi_wepRule: 'La chiave WEP deve essere composta da caratteri ASCII compresi tra 32 e 127,escluso: , " : ; & \\.',
ids_wifi_disconWarning: 'Questa azione comporta la disconnessione della rete Wi-Fi. Continuare?',
ids_wifi_maxSsid: 'La lunghezza massima per il codice SSID è di  32 caratteri, inclusi numeri da 0 a 9, lettera da "a" a "z" (maiuscole e minuscole) e i seguenti simboli: "-", "_", ".", " ".',
ids_wifi_inputSsid: 'Immettere il SSID.',
ids_wifi_wep: 'WEP',
ids_wifi_wpaWpa2Psk: 'WPA/WPA2 PSK',
ids_wifi_wepOpen: 'WEP-OPEN  ',
ids_wifi_wepShare: 'WEP-Shared ',
ids_wifi_wpsActiveWarn: 'Procedura WPS in corso. Attendere 2 minuti e riprovare!',
ids_wifi_ssid2: 'SSID 2,4 GHz',
ids_wifi_cannotSet: 'La rete Wi-Fi è attualmente disattivata, di conseguenza non è possibile eseguire l\'operazione.',
ids_wifi_wifiSecurity: 'Sicurezza Wi-Fi',
ids_wifi_apIsotation: 'Isolamento AP',
ids_wifi_802mode: 'Modalità 802.11',
ids_wifi_channel: 'Canale Wi-Fi',
ids_wifi_maxUser: 'Numero massimo di utenti',
ids_wifi_encryption: 'Crittografia',
ids_wifi_key: 'Chiave',
ids_wifi_pbc: 'PBC',
ids_wifi_pbcConfiguration: 'Configurazione',
ids_wifi_wpsPin: 'PIN WPS',
ids_wifi_pbcDecription: '1. Premere il pulsante WPS del dispositivo finché appare WPS sullo schermo;<br/>2. Sul client (ad es. sul PC), aprire l\'utilità di accesso al Wi-Fi e selezionare PBC;<br/>3. Fare clic sull\'icona in alto.',
ids_wifi_pinDecription: 'PIN:<br/>1. Sul client (ad esempio il PC), selezionare l\'utilità di accesso Wi-Fi che include il supporto WPS (offerto dal fornitore del PC) e selezionare il metodo PIN, quindi verrà generato un codice PIN;<br/>2. Abilitare il PIN e immettere il codice PIN a 4 e 8 cifre;<br/>3. Fare clic su &lt;Applica&gt;.',
ids_wifi_wpsActive: 'WPS attivato.',
ids_wifi_wpsPinRule: 'Il codice PIN WPS deve essere compreso tra 4 e 8 cifre.',
ids_wifi_notSuppotWepWpa: 'WPS non disponibile in WEP, WPA, WPA2 TKIP!',
ids_wifi_notSuppotMacFilter: 'La procedura WPS (versione 2.0) non può essere attivata se il filtro Mac address è abilitato.',
ids_wifi_offTip:'WIFI disabilitato, riprovare dopo averlo riattivato.',
ids_wifi_wpsNotSuppotSSIDHidden: 'SSID nascosta, WPS non disponibile.',
ids_login_loginPwd: 'Password di accesso',
ids_login_newPwd: 'Nuova password',
ids_login_confirmPwdRule: 'La nuova password e la password di conferma devono corrispondere.',
ids_login_inputCurrPwd: 'La password corrente è errata.',
ids_login_wrongPwd: 'Password errata',
ids_login_otherLogin: 'L\'amministratore è già autenticato. Riprovare più tardi.',
ids_login_timeuseout: 'Tentativi di accesso terminati. Riavviare e riprovare.',
ids_login_inputOldPwd: 'Immettere la vecchia password.',
ids_login_inputNewPwd: 'Immettere la nuova password.',
ids_login_inputConfirmPwd: 'Introduzca la contraseña confirmada.',
ids_login_checkPwdRule: 'Contraseña no válida. La longitud de la contraseña de inicio de sesión es de 4 a 16 caracteres, incluidos 0-9, a-z, A-Z,"-+!@$#^&*", vuelva a introducirla.',
ids_login_inputPwd: 'Immettere la password.',
ids_login_nameOrPwdWrong: 'Nome utente o password errati',
ids_login_confirmPwd: 'Conferma password',
ids_router_homeAddr: 'Indirizzo home',
ids_ipAddress: 'Indirizzo IP',
ids_router_dhcpServer: 'Server DHCP',
ids_router_leaseTime: 'Durata del lease dell\'indirizzo IP DHCP',
ids_router_restartWarn: 'Questa azione richiede il riavvio del dispositivo, continuare?',
ids_router_ipAddrEmpty: 'Il campo Indirizzo IP è vuoto. Digitarlo di nuovo !',
ids_router_ipAddrInvalid: 'L\'indirizzo IP non è valido. Digitarlo di nuovo !',
ids_router_subnetEmpty: 'Il campo Subnet mask è vuoto. Digitarlo di nuovo!',
ids_router_subnetInvalid: 'La Subnet mask non è valida. Digitarla di nuovo!',
ids_router_startIpInvalid: 'L\'indirizzo IP iniziale non è valido. Digitarlo di nuovo.',
ids_router_startIpEmpty: 'Il campo Indirizzo IP iniziale è vuoto. Digitarlo di nuovo.',
ids_router_endIpInvalid: 'L\'indirizzo IP finale non è valido. Digitarlo di nuovo.',
ids_router_endIpEmpty: 'Il campo Indirizzo IP finale è vuoto. Digitarlo di nuovo. ',
ids_router_startSameSubnet: 'L\'indirizzo IP iniziale e l\'indirizzo IP devono appartenere alla stessa sottorete.',
ids_router_endSameSubnet: 'L\'indirizzo IP finale e l\'indirizzo IP devono appartenere alla stessa sottorete.',
ids_router_endGeaterStart: 'L\'indirizzo IP finale deve essere maggiore dell\'indirizzo IP iniziale.',
ids_router_startIP: 'Avvia IP',
ids_router_endIP: 'Termina IP',
ids_router_ipRule: 'Errore. Attenzione: il numero 10 dopo l\'indirizzo Home (Home address) rappresenta l\'IP preriservato di sistema e non è possibile includerlo nel DHCP IP Pool.',
ids_sms_saveMode: 'Modalità di salvataggio',
ids_sms_sendingPrompt: 'Invio in corso, attendere. ',
ids_sms_inputNum: 'Immettere il numero di cellulare.',
ids_sms_mobileNumRule: 'La lunghezza massima per un numero di cellulare è di 20 cifre, compresi i caratteri "+0123456789". Immettere nuovamente il numero.',
ids_sms_deleteWarning: 'Elimina SMS?',
ids_sms_saveDevice: 'Dispositivo',
ids_sms_saveSimCard: 'scheda SIM',
ids_sms_smsFull: 'La casella SMS è piena. Eliminare alcuni SMS per inviarne/salvarne di nuovi.',
ids_sms_selectSomeOptions: '3 contatti al massimo',
ids_sms_selectAnOption: 'Seleziona un\'opzione',
ids_sms_chatInputConfirm: 'Premere Invio o immettere ";" per completare l\'operazione',
ids_sms_phoneNumberInvalid: 'Numero di telefono non valido',
ids_sms_draft: 'Bozza',
ids_sms_saveDraftSuccess: 'SMS salvato come bozza',
ids_sms_saveDraftFailed: 'Salvataggio bozza non riuscito',
ids_sms_newMessageOn: 'non letto di',
ids_sms_messageSending: 'È in corso l\'invio di un SMS',
ids_sms_newMessage: 'Nuovo messaggio',
ids_sms_deleteAll: 'Elimina tutto',
ids_sms_centerNum: 'Centro SMS',
ids_sms_report: 'Rapporto di consegna SMS',
ids_sms_emptyMessageWarn: 'Il messaggio è vuoto. Inviarlo comunque?',
ids_sms_numberWarning: 'Il testo immesso è troppo lungo. Eliminarne una parte.',
ids_sms_sendFail: 'Invio SMS non riuscito.',
ids_sms_delivered: 'Consegnato',
ids_wan_connected: 'Connesso ',
ids_wan_connecting: 'Connessione in corso... ',
ids_wan_disconnected: 'Disconnesso',
ids_wan_disconnecting: 'Disconnessione in corso…',
ids_wan_tips: 'Fallito! Azzeerare piano dati mensile e riconnettere.',
ids_wan_roamingAutoConnect: 'Connessione automatica anche in roaming',
ids_wan_inputDeviceName: 'immettere nome dispositivo',
ids_wan_connectIPMode: 'Modalità Connessione IP',
ids_wan_cannotBlock: 'Il Filtro MAC è Permetti ora, non è possibile processare questa opzione.',
ids_wan_Block: 'La lista degli indirizzi MAC è piena, non è possibile processare questa opzione.',
ids_sys_ipAddress: 'Indirizzo IP',
ids_sys_swVersion: 'Versione software',
ids_sys_hwVersion: 'Versione hardware',
ids_sys_imei: 'IMEI',
ids_sys_deviceName: 'Nome dispositivo',
ids_sys_macAddress: 'Indirizzo MAC',
ids_sys_rebootDecription: 'Fare clic su questo pulsante per riavviare il dispositivo.',
ids_sys_backupDecription: 'Scarica (esegui backup) la configurazione.',
ids_sys_setRebootEvent: 'È in corso il riavvio del dispositivo, attendere 60 secondi quindi fare riconnettersi al dispositivo Wi-Fi.',
ids_sys_resetDecription: 'Reimposta i valori predefiniti.',
ids_sys_selectFilePrompt: 'Selezionare un file prima di procedere al caricamento.',
ids_sys_restoreBackupWarn: 'Questa azione aggiornerà le impostazioni e riavvierà il dispositivo al termine del caricamento; continuare? ',
ids_sys_restoreFactoryWarn: 'Questa azione riporterà le impostazioni sui valori predefiniti e riavvierà il dispositivo; continuare? ',
ids_sys_system: 'sistema',
ids_sys_rebootWarn: 'Riavviare il dispositivo?',
ids_security_macFilterDescription: 'Per controllare e gestire il dispositivo mediante l\'accesso a WLAN e migliorare la protezione di WLAN. ',
ids_security_macAddrInvalid: 'Indirizzo MAC non valido.',
ids_security_macAddrNameWarn: 'Indirizzo MAC già esistente.',
ids_security_addMacAddress: 'Aggiungi indirizzo MAC',
ids_sd_sdSharing: 'Condivisione della scheda SD',
ids_sd_currentFolder: 'Cartella corrente',
ids_sd_dlna: 'DLNA',
ids_sd_close: 'Chiudi',
ids_sd_serverName: 'Nome server',
ids_sd_dlnaDes: 'Attivando DLNA, il contenuto multimediale presente sulla scheda microSD sarà disponibile anche per il dispositivo connesso.',
ids_sd_usedTotal: '(Utilizzato/Totale)',
ids_sd_noSdCard: 'Nessuna scheda SD',
ids_sd_viewFile: 'Visualizza file',
ids_sd_sdShareMode: 'Modo condividi SD',
ids_sd_sdCard: 'SD Card',
ids_fota_checking: 'Controllo in corso…',
ids_fota_checkUpdate: 'Aggiorna',
ids_fota_updateTitle: 'Aggiornamenti sistema',
ids_fota_upgrading: 'Aggiornamento in corso...',
ids_fota_upgradingTips: 'Non spegnere durante l\'aggiornamento. Il dispositivo verrà riavviato dopo l\'aggiornamento.',
ids_fota_downloading: 'Download in corso…',
ids_fota_batteryTips: 'Livello batteria troppo basso per aggiornare il dispositivo',
ids_fota_downloadError: 'Errore download',
ids_fota_findNewVersion: 'Trova nuova versione',
ids_fota_updateDescription: 'fare clic su "Aggiorna" per aggiornare alla nuova versione.',
ids_fota_latestVersion: 'Questa è già la versione più recente.',
ids_fota_haveNewVersion: 'Nuovo SW disponibile. Fare clic per aggiornare.',
ids_more_onlineUpdate: 'Aggiornamento online',
ids_sys_chooseFile:'Scegli file',
ids_sys_noFileChosen:'Nessun file è stato scelto',
ids_tr069_client:'Client TR-069 – Configurazione',
ids_tr069_tips:'Selezionare i valori desiderati e fare clic su "Applica/Salva" per configurare le opzioni del client TR-069.',
ids_tr069_inform:'Inform',
ids_tr069_informInterval:'Intervallo Inform',
ids_tr069_acsUrl:'ACS URL',
ids_tr069_acsUsername:'Nome utente ACS',
ids_tr069_acsPw:'Password ACS',
ids_tr069_connRqAuth:'Autenticazione richiesta di connessione',
ids_tr069_connRqUsername:'Nome utente richiesta di connessione',
ids_tr069_connRqPw:'Password richiesta di connessione',
ids_tr069_inputInformInterval:'Immettere intervallo prima di salvare',
ids_tr069_inputAcsUrl:'Immettere ACS URL prima di salvare',
ids_tr069_inputAcsUserName:'Immettere nome utente ACS prima di salvare',
ids_tr069_inputAcsPassword:'Immettere password ACS prima di salvare',
ids_tr069_inputConReqUserName:'Immetere nome utente per richiesta connesione prima di salvare',
ids_tr069_inputConReqPassword:'Immettere password richiesta di connessione prima di salvare',
ids_tr069_informIntervalRule:'L\'intervallo deve essere 0-2678400,inclusi "0123456789".',
ids_tr069_acsUrlRule:'Formato ACS url: eg:http://ip address:port/xxx',
ids_wifi_country:'Paese',
ids_wifi_wlan_mode:'Modalità Wlan'
}