var resourceInfo={
ids_error: '¡Error!',
ids_login: 'Iniciar',
ids_auto: 'AUTO',
ids_automatic: 'Automático',
ids_manual: 'Manual',
ids_enable: 'Habilitado',
ids_validate: 'Validar',
ids_modify: 'Modificar',
ids_disable: 'Deshabilitar',
ids_subnetMask: 'Máscara de subred',
ids_allow: 'Permitir',
ids_deny: 'Denegar',
ids_day: 'día',
ids_days: 'días',
ids_hour: 'hora',
ids_hours: 'horas',
ids_minute: 'minuto',
ids_minutes: 'minutos',
ids_requestError: 'No hay respuesta; puede que se haya desconectado el dispositivo. Reinicie el dispositivo y vuelva a intentarlo.',
ids_success: '¡Correcto!',
ids_fail: '¡Error!',
ids_back: 'Atrás',
ids_icon_battery: 'Batería',
ids_icon_timeElapsed: 'Tiempo transcurrido',
ids_icon_debit: 'Débito',
ids_icon_people: 'Contactos',
ids_icon_downloaded: 'Descargadas',
ids_icon_uploaded: 'Cargadas',
ids_menu_connection: 'Conexión',
ids_menu_sms: 'SMS',
ids_menu_settings: 'Configuración',
ids_menu_smsSettings: 'Configuración de SMS',
ids_menu_connectDevice: 'Dispositivo(s) conectado(s)',
ids_menu_usage: 'Uso',
ids_menu_sharing: 'Compartir',
ids_menu_usageSetting: 'Ajustes de uso',
ids_menu_more: 'Más',
ids_menu_language:'Idioma',
ids_foot_copyright: 'Copyright 2014-2016 TCL Communication Ltd. Todos los derechos reservados.',
ids_btn_help: 'Ayuda',
ids_btn_logout: 'Cerrar',
ids_btn_block: 'Bloquear',
ids_btn_unblock: 'Desbloquear',
ids_btn_apply: 'Aplicar',
ids_btn_cancel: 'Cancelar',
ids_btn_next: 'Siguiente',
ids_btn_continue: 'Continuar',
ids_btn_save: 'Guardar',
ids_btn_new: 'Nuevo',
ids_btn_edit: 'Editar',
ids_btn_delete: 'Eliminar',
ids_btn_setDefault: 'Fijar&nbsp;predeterm.',
ids_btn_refresh: 'Actualizar',
ids_btn_select: 'Seleccionar',
ids_btn_reboot: 'Reiniciar',
ids_btn_reset: 'Restablecer',
ids_btn_backup: 'Copia de seguridad',
ids_btn_restore: 'Restablecer',
ids_btn_ok: 'Aceptar',
ids_btn_previous: 'Anterior',
ids_btn_add: 'Añadir',
ids_title_wps: 'WPS',
ids_title_advanced: 'Configuración avanzada',
ids_title_blockDevice: 'Bloquear dispositivo',
ids_title_connectMode: 'Modo de conexión',
ids_title_networkMode: 'Modo de red',
ids_title_macFilter: 'Filtro de MAC',
ids_title_loginSettings: 'Ajustes de inicio de sesión',
ids_title_pinCodeSettings: 'Ajustes del código PIN',
ids_title_profilesManagement: 'Gestión de perfiles',
ids_title_wifiSettings: 'Ajustes de Wi-Fi',
ids_title_about: 'Acerca de',
ids_title_tr069:'TR069',
ids_net_registing: 'Registrando......',
ids_net_select: 'Selección de red',
ids_net_4gOnly: 'Solo 4G',
ids_net_3gOnly: 'Solo 3G',
ids_net_2gOnly: 'Solo 2G',
ids_net_operator: 'Operador',
ids_net_noService: 'Sin servicio',
ids_net_service: 'Servicio',
ids_net_status: 'Estado',
ids_net_searching: 'Buscando......',
ids_net_gsm: '2G',
ids_net_umts: '3G',
ids_net_lte: '4G',
ids_net_active: 'Activo',
ids_net_available: 'Disponible',
ids_net_forbid: 'Prohibido',
ids_net_selectWarn: 'Seleccione una red.',
ids_sim_pinManagement: 'Administración del código PIN',
ids_sim_remainTime: 'Intento(s) restante(s)',
ids_sim_pinCode: 'Código PIN',
ids_sim_pukCode: 'Código PUK',
ids_sim_simLockCode: 'Código de bloqueo de la SIM',
ids_sim_newPinCode: 'Código PIN nuevo',
ids_sim_confirmPinCode: 'Código PIN confirmado',
ids_sim_lockForbidden: '¡SIMLOCK prohibido!',
ids_sim_noSimCard: 'No hay tarjeta SIM',
ids_sim_invalidSimCard: 'Tarjeta SIM no válida',
ids_sim_pinNotAvailable: 'El código PIN no está disponible.',
ids_sim_initializing: 'La SIM se está inicializando.',
ids_sim_pinRequired: 'Se requiere PIN',
ids_sim_pukRequired: 'Se requiere PUK',
ids_sim_unknown: 'Desconocido',
ids_sim_nck: 'NCK',
ids_sim_nsck: 'NSCK',
ids_sim_spck: 'SPCK',
ids_sim_cck: 'CCK',
ids_sim_pck: 'PCK',
ids_sim_rck: 'RCK',
ids_sim_simLocked: 'Se requiere bloqueo de la SIM',
ids_sim_pinRequiredTips: 'Para obtener más información, haga clic en "Se requiere PIN" para desbloquear desde el principio.',
ids_sim_pukRequiredTips: 'Para obtener más información, haga clic en "Se requiere PUK" para desbloquear desde el principio.',
ids_sim_simLockedTips: 'Para obtener más información, haga clic en "Se requiere bloqueo de la SIM" para desbloquear desde el principio.',
ids_sim_pinConfirmed: 'El código PIN confirmado debe ser el mismo que el nuevo código PIN.',
ids_sim_pinRule: 'El código PIN debe contener entre 4 y 8 dígitos.',
ids_sim_pukRule: 'El código PUK debe contener 8 dígitos.',
ids_sim_newPinRule: 'El nuevo código PIN debe contener entre 4 y 8 dígitos.',
ids_sim_comfirmPinRule: 'El código PIN confirmado debe contener entre 4 y 8 dígitos.',
ids_sim_lockCodeRule: 'El código SIMLOCK debe tener 10 dígitos.',
ids_sim_pinEnable: 'La validación automática del PIN está activada.',
ids_sim_pinDisable: 'La validación automática del PIN está desactivada.',
ids_sim_autoPinState: 'Estatus actual',
ids_sim_autoValidate: 'Auto validar',
ids_sim_pinCodeOperation: 'Funciones del código PIN',
ids_sim_pinError: '¡PIN incorrecto!',
ids_sim_changePinError: '¡Error al cambiar el PIN!',
ids_sim_pukError: '¡PUK incorrecto!',
ids_sim_simlockError: '¡Error de bloqueo de la SIM!',
ids_sim_autoPin: 'Validación automática del código PIN',
ids_sim_autoPinError: '¡Error de verificación automática del PIN!',
ids_profile_password: 'Contraseña',
ids_profile_profileName: 'Nombre de perfil',
ids_profile_userName: 'Nombre de usuario',
ids_profile_apn: 'APN',
ids_profile_protocal: 'Protocolo',
ids_profile_deleteWarn: '¿Está seguro de que quiere eliminar?',
ids_profile_inputName: 'Introduzca el nombre del perfil antes de guardarlo.',
ids_profile_profileNameRule: 'El número máximo de caracteres para el nombre del perfil es 31, sin incluir: , " : ; \\ & % + < > ?.',
ids_profile_userNameRule: 'El número máximo de caracteres para el nombre de usuario es 31, sin incluir: , " : ; & \\.',
ids_profile_inputDialNum: '¡Introduzca el número de marcación!',
ids_profile_inputApn: '¡Introduzca el APN!',
ids_profile_numRule: 'Nota: El número máximo del perfil que puede crear es 15.',
ids_profile_dialNumber: 'Número de marcación',
ids_profile_inputRule: 'La APN & Número de marcación debe estar formada por caracteres ASCII entre 32 y 127, sin incluir: , " : ; & \\.',
ids_profile_pwdRule: 'El número máximo de caracteres para la contraseña es 31, sin incluir " : ; & \\.',
ids_profile_nameWarn: 'El nombre del perfil ya existe.',
ids_usage_duration: 'Duración',
ids_usage_clearHistory: '¿Seguro que quiere reiniciar todas las estadísticas?',
ids_usage_clear: 'Borrar historial',
ids_usage_home: 'Personal',
ids_usage_roaming: 'Roaming',
ids_usage_of: 'de ',
ids_usage_billingDay: 'Día de facturación',
ids_usage_monthlyDataPlan: 'Plan mensual de datos',
ids_usage_dataConsumption: 'Consumo de datos',
ids_usage_day: 'día',
ids_usage_timeLimit: 'Límite de tiempo',
ids_usage_setTimeLimit: 'Ajustar límite de tiempo',
ids_usage_minutesTimes: 'Min(s)',
ids_usage_hrs: 'Hrs',
ids_usage_timePassed: 'Tiempo superado',
ids_usage_autoDisconnected: 'Desconectado automáticamente',
ids_usage_dataUsageReach: 'Cuando el uso de datos alcanza al plan de datos mensual',
ids_usage_hours: 'horas',
ids_usage_minutes: 'minutos',
ids_usage_billingTimeTips: 'Introduzca el día entre 1 y 31.',
ids_usage_mothlyDataTips: 'Introduzca la fecha entre 1 y 1024.',
ids_usage_startTimeTips: 'Introduzca la fecha entre 1 y 43200',
ids_wifi_offRule: 'Actualmente, WiFi está desactivado ya que ningún equipo se ha conectado desde hace mucho tiempo. Por favor, habilite WiFi manualmente presionando cualquier botón del dispositivo.',
ids_wifi_wifi: 'Wi-Fi',
ids_wifi_on: 'Activado',
ids_wifi_off: 'Desactivado',
ids_wifi_ssidBroadcast: 'Difusión SSID',
ids_wifi_securityDisableDes: 'Desactivar significa cancelar la clave Wi-Fi.',
ids_wifi_cipher: 'Tipo de cifrado',
ids_wifi_wpaTkip: 'TKIP',
ids_wifi_wpaAes: 'AES',
ids_wifi_showPwd: 'Mostrar contraseña',
ids_wifi_wpa: 'PSK del WPA',
ids_wifi_wpa2: 'PSK del WPA2',
ids_wifi_wepDescription: 'La clave WEP tiene 5 o 13 caracteres ASCII, o bien 10 o 26 caracteres hexadecimales.',
ids_wifi_wpaDescription: 'La clave precompartida (PSK) del WPA debe contener entre 8 y 63 caracteres ASCII o 64 dígitos hexadecimales.',
ids_wifi_wpaRule: 'La PSK del WPA debe estar formada por caracteres ASCII entre 32 y 127, sin incluir: , " : ; & \\.',
ids_wifi_wepRule: 'La clave WEP debe estar formada por caracteres ASCII entre 32 y 127, sin incluir: , " : ; & \\.',
ids_wifi_disconWarning: 'Esta acción desconectará el Wi-Fi. ¿Aún desea continuar?',
ids_wifi_maxSsid: 'El número máximo de caracteres para el SSID es 32, incluidos 0-9, a-z, A-Z, "-", "_", "." ," ".',
ids_wifi_inputSsid: 'Introduzca el SSID.',
ids_wifi_wep: 'WEP',
ids_wifi_wpaWpa2Psk: 'WPA/WPA2 PSK',
ids_wifi_wepOpen: ' WEP-OPEN',
ids_wifi_wepShare: 'WEP-Shared',
ids_wifi_wpsActiveWarn: 'Se está ejecutando el procedimiento WPS.Espere 2 minutos y vuelva a intentarlo.',
ids_wifi_ssid2: 'SSID 2,4 GHz',
ids_wifi_cannotSet: 'Wi-Fi está deshabilitado, no se puede procesar esta opción.',
ids_wifi_wifiSecurity: 'Seguridad de Wi-Fi',
ids_wifi_apIsotation: 'Aislamiento AP',
ids_wifi_802mode: 'Modo 802.11',
ids_wifi_channel: 'Canal Wi-Fi ',
ids_wifi_maxUser: 'Número máximo de usuarios',
ids_wifi_encryption: 'Codificación',
ids_wifi_key: 'Tecla',
ids_wifi_pbc: 'CP',
ids_wifi_pbcConfiguration: 'configuración del pulsador',
ids_wifi_wpsPin: 'PIN WPS',
ids_wifi_pbcDecription: '1. Pulse el botón WPS de este dispositivo hasta que en la pantalla aparezca WPS;<br/>2. En el cliente (p. ej., PC), abra la utilidad de acceso Wi-Fi y seleccione la CP;<br/>3. Haga clic en el icono de la parte superior.',
ids_wifi_pinDecription: 'PIN:<br/>1. En el cliente (p. ej., PC), abra la red Wi-Fi y seleccione el método PIN, a continuación, se generará un código PIN de 4 u 8 dígitos;<br/>2. Active el PIN e introduzca el código PIN de 4 u 8 dígitos;<br/>3. Haga clic en &lt;Aplicar&gt;.',
ids_wifi_wpsActive: 'WPS activada.',
ids_wifi_wpsPinRule: 'El código PIN WPS debe contener entre 4 u 8 dígitos.',
ids_wifi_notSuppotWepWpa: 'WPS no disponible con WEP, WPA, WPA2 TKIP',
ids_wifi_notSuppotMacFilter: 'WPS (Versión 2.0) no puede ser activado si el filtrado por dirección Mac está habilitado.',
ids_wifi_offTip: 'WiFi esta deshabilitado. Por favor, inténtelo de nuevo tras haber habilitado WiFi.',
ids_wifi_wpsNotSuppotSSIDHidden: 'SSID oculto, imposible configurar WPS.',
ids_login_loginPwd: 'Contraseña de inicio de sesión',
ids_login_newPwd: 'Contraseña nueva',
ids_login_confirmPwdRule: 'La nueva contraseña y la confirmada deben ser la misma.',
ids_login_inputCurrPwd: 'La contraseña actual es incorrecta.',
ids_login_wrongPwd: 'Contraseña incorrecta',
ids_login_otherLogin: 'El administrador ya ha iniciado sesión, inténtelo más tarde.',
ids_login_timeuseout: 'Ha superado el número de intentos de registro. Por favor, reinicie y vuelva a intentarlo.',
ids_login_inputOldPwd: 'Introduzca la contraseña antigua.',
ids_login_inputNewPwd: 'Introduzca la nueva contraseña.',
ids_login_inputConfirmPwd: 'Por favor, confirme la contraseña.',
ids_login_checkPwdRule: 'Contraseña no válida. La longitud de la contraseña es de 4 a 16 caracteres, incluidos 0-9, a-z, A-Z,"-+!@$#^&*", por favor vuelva a introducirla.',
ids_login_inputPwd: 'Introduzca el contraseña.',
ids_login_nameOrPwdWrong: 'El nombre de usuario o la contraseña son incorrectos',
ids_login_confirmPwd: 'Confirme la contraseña',
ids_router_homeAddr: 'Domicilio',
ids_ipAddress: 'Dirección IP',
ids_router_dhcpServer: 'Servidor DHCP',
ids_router_leaseTime: 'Tiempo de concesión de IP de DHCP',
ids_router_restartWarn: 'Esta acción requiere que se reinicie el dispositivo. ¿Aún desea continuar?',
ids_router_ipAddrEmpty: '¡La dirección IP está vacía. Vuelva a introducirla !',
ids_router_ipAddrInvalid: '¡La dirección IP no es válida. Vuelva a introducirla !',
ids_router_subnetEmpty: '¡La máscara de subred está vacía. Vuelva a introducirla!',
ids_router_subnetInvalid: '¡La máscara de subred no es válida. Vuelva a introducirla!',
ids_router_startIpInvalid: '¡La dirección IP inicial no es válida. Vuelva a introducirla!',
ids_router_startIpEmpty: '¡La dirección IP inicial está vacía. Vuelva a introducirla!',
ids_router_endIpInvalid: '¡La dirección IP final no es válida. Vuelva a introducirla!',
ids_router_endIpEmpty: '¡La dirección IP final está vacía. Vuelva a introducirla!',
ids_router_startSameSubnet: 'La "dirección IP inicial" y la "dirección IP" deben pertenecer a la misma subred.',
ids_router_endSameSubnet: 'La "dirección IP final" y la "dirección IP" deben pertenecer a la misma subred.',
ids_router_endGeaterStart: 'La "dirección IP final" debe ser mayor que la "dirección IP inicial".',
ids_router_startIP: 'Dirección IP inicial',
ids_router_endIP: 'Dirección IP final',
ids_router_ipRule: 'Error. Tenga en cuenta que 10 después de la dirección principal es una IP reservada previamente por el sistema, y no puede incluirse en el grupo de IP de DHCP.',
ids_sms_saveMode: 'Modo ahorro',
ids_sms_sendingPrompt: 'Enviando, espere.',
ids_sms_inputNum: 'Introduzca un número de móvil.',
ids_sms_mobileNumRule: 'El número máximo de caracteres para el número de móvil es 20 dígitos, incluido "+0123456789", vuelva a introducirlo.',
ids_sms_deleteWarning: '¿Desea eliminarla?',
ids_sms_saveDevice: 'Dispositivo',
ids_sms_saveSimCard: 'Tarjeta SIM',
ids_sms_smsFull: 'El buzón de SMS está lleno, elimine algunos SMS para poder enviar/guardar SMS nuevos.',
ids_sms_selectSomeOptions: '3 contactos como máximo',
ids_sms_selectAnOption: 'Seleccione una opción',
ids_sms_chatInputConfirm: 'Pulse Intro o introduzca ";" para completar',
ids_sms_phoneNumberInvalid: 'El número de teléfono no es válido',
ids_sms_draft: 'Borradores',
ids_sms_saveDraftSuccess: 'El SMS se ha guardado como borrador',
ids_sms_saveDraftFailed: 'Error al guardar borrador',
ids_sms_newMessageOn: 'sin leer de ',
ids_sms_messageSending: 'Envío de un SMS en curso',
ids_sms_newMessage: 'Nuevo mensaje',
ids_sms_deleteAll: 'Eliminar todo',
ids_sms_centerNum: 'Centro de SMS',
ids_sms_report: 'Reporte SMS',
ids_sms_emptyMessageWarn: 'El mensaje está vacío. ¿Seguro que desea enviar este mensaje vacío?',
ids_sms_numberWarning: 'El texto introducido es demasiado largo. Borre alguna parte.',
ids_sms_sendFail: '¡Error de envío del SMS!',
ids_sms_delivered: 'Entregado',
ids_wan_connected: 'Conectada',
ids_wan_connecting: 'Conectando......',
ids_wan_disconnected: 'Desconectada',
ids_wan_disconnecting: 'Desconectando......',
ids_wan_tips: '¡Falló ! Desbordamiento en el histórico de uso, usted puede reiniciar el Plan Mensual de Datos y luego reconectarse.',
ids_wan_roamingAutoConnect: 'Conectar automáticamente incluso en roaming.',
ids_wan_inputDeviceName: 'Introduzca un nombre de dispositivo',
ids_wan_connectIPMode: 'Modo de conexión IP',
ids_wan_cannotBlock: 'El filtrado por MAC está habilitado ahora, no se puede procesar esta opción.',
ids_wan_Block: 'La lista de direcciones MAC está llena, no se puede procesar esta opción.',
ids_sys_ipAddress: 'Dirección IP',
ids_sys_swVersion: 'Versión de software',
ids_sys_hwVersion: 'Versión de hardware',
ids_sys_imei: 'IMEI',
ids_sys_deviceName: 'Nombre del dispositivo',
ids_sys_macAddress: 'Dirección MAC',
ids_sys_rebootDecription: 'Haga clic en este botón para reiniciar el dispositivo.',
ids_sys_backupDecription: 'Descargar (hacer una copia de seguridad) la configuración.',
ids_sys_setRebootEvent: 'Se está reiniciando el dispositivo, espere 60 segundos y, a continuación, haga vuelva a conectarse al dispositivo Wi-Fi.',
ids_sys_resetDecription: 'Restablecer la configuración predeterminada de fábrica.',
ids_sys_selectFilePrompt: 'Seleccione un archivo antes de iniciar la carga.',
ids_sys_restoreBackupWarn: 'Esta acción actualizará la configuración y reiniciará el dispositivo una vez que haya finalizado la descarga. ¿Aún desea continuar?',
ids_sys_restoreFactoryWarn: 'Esta acción restablece la configuración predeterminada de fábrica y reinicia el dispositivo. ¿Aún desea continuar?',
ids_sys_system: 'Sistema',
ids_sys_rebootWarn: '¿Desea reiniciar el dispositivo?',
ids_security_macFilterDescription: 'Control y administración del dispositivo que accede a la WLAN (mejora de la seguridad de la WLAN).',
ids_security_macAddrInvalid: 'La dirección MAC no es válida.',
ids_security_macAddrNameWarn: 'La dirección MAC ya existe.',
ids_security_addMacAddress: 'Añadir dirección MAC',
ids_sd_sdSharing: 'Compartir tarjeta SD',
ids_sd_currentFolder: 'Carpeta actual',
ids_sd_dlna: 'DLNA',
ids_sd_close: 'Cerrar',
ids_sd_serverName: 'Nombre del servidor',
ids_sd_dlnaDes: 'Al activar DLNA, los contenidos multimedia de la tarjeta microSD pasan a estar disponibles para el dispositivo conectado.',
ids_sd_usedTotal: '(Usados/Total)',
ids_sd_noSdCard: 'Sin tarjeta SD',
ids_sd_viewFile: 'Ver archivo',
ids_sd_sdShareMode: 'Modo Compartir SD',
ids_sd_sdCard: 'Tarjeta SD',
ids_fota_checking: 'Comprobando…',
ids_fota_checkUpdate: 'Actualizar',
ids_fota_updateTitle: 'Actualizaciones del sistema',
ids_fota_upgrading: 'Actualizando...',
ids_fota_upgradingTips: 'No apague el dispositivo durante la actualización. El dispositivo se reiniciará después de la actualización.',
ids_fota_downloading: 'Descargando…',
ids_fota_batteryTips: 'Batería baja, el dispositivo no puede actualizarse',
ids_fota_downloadError: 'Error de descarga',
ids_fota_findNewVersion: 'Buscar nueva versión ',
ids_fota_updateDescription: 'Haga clic en "Actualizar" para actualizar a la nueva versión.',
ids_fota_latestVersion: 'Esta ya es la última versión.',
ids_fota_haveNewVersion: 'Hay un nuevo software disponible; haga clic para actualizar.',
ids_more_onlineUpdate: 'Actualización online',
ids_sys_chooseFile:'Seleccione el archivo',
ids_sys_noFileChosen:'Archivo no seleccionado',
ids_tr069_client:'Configuración del cliente TR-069',
ids_tr069_tips:'Seleccione los valores deseados y haga clic en “Aplicar/Guardar” para configurar las opciones del cliente TR-069.',
ids_tr069_inform:'Informar',
ids_tr069_informInterval:'Informar del intervalo',
ids_tr069_acsUrl:'ACS URL',
ids_tr069_acsUsername:'Nombre de usuario ACS',
ids_tr069_acsPw:'Contraseña de ACS',
ids_tr069_connRqAuth:'Autenticación de solicitud de conexión',
ids_tr069_connRqUsername:'Nombre de usuario de solicitud de conexión',
ids_tr069_connRqPw:'Contraseña de solicitud de conexión',
ids_tr069_inputInformInterval:'Por favor, introduzca el intervalo de información antes de guardar.',
ids_tr069_inputAcsUrl:'Por favor, introduzca la dirección URL del ACS antes de guardar.',
ids_tr069_inputAcsUserName:'Por favor, introduzca el nombre de usuario del ACS antes de guardar.',
ids_tr069_inputAcsPassword:'Por favor, introduzca la contraseña del ACS antes de guardar.',
ids_tr069_inputConReqUserName:'Por favor, introduzca el nombre de usuario de la petición de conexión antes de guardar.',
ids_tr069_inputConReqPassword:'Por favor, introduzca la contraseña de la petición de conexión antes de guardar.',
ids_tr069_informIntervalRule:'El intervalo de información debe estar entre 0 y 2678400.',
ids_tr069_acsUrlRule:'Formato de URL ACS: ej.http://direccionip:puerto/xxx',
ids_wifi_country:'País',
ids_wifi_wlan_mode:'Modo Wlan'
}