#!/bin/sh
echo "Content-type: text/html"
echo ""
if [ ! -f /usr/bin/diagcmd ]; then
    echo '{"error": "diagcmd not found"}'
    exit 0
fi

SUCESS="4b1326000b3600000000"

CA77STATUS=$(/usr/bin/diagcmd 4B 13 26 00 08 00 00 00 40 00 08 00 0B 36 44 00 08 00 00 00 00 00 2F 6E 76 2F 69 74 65 6D 5F 66 69 6C 65 73 2F 72 66 6E 76 2F 30 30 30 32 35 32 31 34 00 | tr -d " ")

if [ "$CA77STATUS" = "$SUCESS" ]; then
    echo '{"CA77": "enabled"}'
    exit 0
fi

echo '{"error": "something wrong"}'
exit 0